/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: obu_apollo.proto */

#ifndef PROTOBUF_C_obu_5fapollo_2eproto__INCLUDED
#define PROTOBUF_C_obu_5fapollo_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Obstacle Obstacle;
typedef struct _ObuMsg ObuMsg;


/* --- enums --- */

/*
 * 障碍物类型
 */
typedef enum _TYPE {
  /*
   * 人
   */
  TYPE__HUMAN = 1,
  /*
   * 车
   */
  TYPE__VEHICLE = 2,
  /*
   * 其他障碍
   */
  TYPE__OTHER = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(TYPE)
} TYPE;

/* --- messages --- */

/*
 * 单个障碍
 */
struct  _Obstacle
{
  ProtobufCMessage base;
  /*
   * 预留
   */
  int32_t id;
  /*
   * 障碍物类型
   */
  TYPE type;
  /*
   * 实际经度 * 10的七次方
   */
  int32_t lng;
  /*
   * 实际纬度 * 10的七次方
   */
  int32_t lat;
};
#define OBSTACLE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&obstacle__descriptor) \
    , 0, 0, 0, 0 }


/*
 * 要传给Apollo的
 */
struct  _ObuMsg
{
  ProtobufCMessage base;
  /*
   * 一个累加的数
   */
  uint32_t count;
  /*
   * 障碍的数组
   */
  size_t n_obs;
  Obstacle **obs;
};
#define OBU_MSG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&obu_msg__descriptor) \
    , 0, 0,NULL }


/* Obstacle methods */
void   obstacle__init
                     (Obstacle         *message);
size_t obstacle__get_packed_size
                     (const Obstacle   *message);
size_t obstacle__pack
                     (const Obstacle   *message,
                      uint8_t             *out);
size_t obstacle__pack_to_buffer
                     (const Obstacle   *message,
                      ProtobufCBuffer     *buffer);
Obstacle *
       obstacle__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   obstacle__free_unpacked
                     (Obstacle *message,
                      ProtobufCAllocator *allocator);
/* ObuMsg methods */
void   obu_msg__init
                     (ObuMsg         *message);
size_t obu_msg__get_packed_size
                     (const ObuMsg   *message);
size_t obu_msg__pack
                     (const ObuMsg   *message,
                      uint8_t             *out);
size_t obu_msg__pack_to_buffer
                     (const ObuMsg   *message,
                      ProtobufCBuffer     *buffer);
ObuMsg *
       obu_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   obu_msg__free_unpacked
                     (ObuMsg *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Obstacle_Closure)
                 (const Obstacle *message,
                  void *closure_data);
typedef void (*ObuMsg_Closure)
                 (const ObuMsg *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    type__descriptor;
extern const ProtobufCMessageDescriptor obstacle__descriptor;
extern const ProtobufCMessageDescriptor obu_msg__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_obu_5fapollo_2eproto__INCLUDED */
