/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: vision.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "vision.pb-c.h"
void   vision__data_time__init
                     (Vision__DataTime         *message)
{
  static const Vision__DataTime init_value = VISION__DATA_TIME__INIT;
  *message = init_value;
}
size_t vision__data_time__get_packed_size
                     (const Vision__DataTime *message)
{
  assert(message->base.descriptor == &vision__data_time__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vision__data_time__pack
                     (const Vision__DataTime *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vision__data_time__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vision__data_time__pack_to_buffer
                     (const Vision__DataTime *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vision__data_time__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vision__DataTime *
       vision__data_time__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vision__DataTime *)
     protobuf_c_message_unpack (&vision__data_time__descriptor,
                                allocator, len, data);
}
void   vision__data_time__free_unpacked
                     (Vision__DataTime *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vision__data_time__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vision__pedestrian__init
                     (Vision__Pedestrian         *message)
{
  static const Vision__Pedestrian init_value = VISION__PEDESTRIAN__INIT;
  *message = init_value;
}
size_t vision__pedestrian__get_packed_size
                     (const Vision__Pedestrian *message)
{
  assert(message->base.descriptor == &vision__pedestrian__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vision__pedestrian__pack
                     (const Vision__Pedestrian *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vision__pedestrian__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vision__pedestrian__pack_to_buffer
                     (const Vision__Pedestrian *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vision__pedestrian__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vision__Pedestrian *
       vision__pedestrian__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vision__Pedestrian *)
     protobuf_c_message_unpack (&vision__pedestrian__descriptor,
                                allocator, len, data);
}
void   vision__pedestrian__free_unpacked
                     (Vision__Pedestrian *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vision__pedestrian__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vision__obstacle__init
                     (Vision__Obstacle         *message)
{
  static const Vision__Obstacle init_value = VISION__OBSTACLE__INIT;
  *message = init_value;
}
size_t vision__obstacle__get_packed_size
                     (const Vision__Obstacle *message)
{
  assert(message->base.descriptor == &vision__obstacle__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vision__obstacle__pack
                     (const Vision__Obstacle *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vision__obstacle__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vision__obstacle__pack_to_buffer
                     (const Vision__Obstacle *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vision__obstacle__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vision__Obstacle *
       vision__obstacle__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vision__Obstacle *)
     protobuf_c_message_unpack (&vision__obstacle__descriptor,
                                allocator, len, data);
}
void   vision__obstacle__free_unpacked
                     (Vision__Obstacle *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vision__obstacle__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vision__abnormal_car__init
                     (Vision__AbnormalCar         *message)
{
  static const Vision__AbnormalCar init_value = VISION__ABNORMAL_CAR__INIT;
  *message = init_value;
}
size_t vision__abnormal_car__get_packed_size
                     (const Vision__AbnormalCar *message)
{
  assert(message->base.descriptor == &vision__abnormal_car__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vision__abnormal_car__pack
                     (const Vision__AbnormalCar *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vision__abnormal_car__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vision__abnormal_car__pack_to_buffer
                     (const Vision__AbnormalCar *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vision__abnormal_car__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vision__AbnormalCar *
       vision__abnormal_car__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vision__AbnormalCar *)
     protobuf_c_message_unpack (&vision__abnormal_car__descriptor,
                                allocator, len, data);
}
void   vision__abnormal_car__free_unpacked
                     (Vision__AbnormalCar *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vision__abnormal_car__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vision__special_car__init
                     (Vision__SpecialCar         *message)
{
  static const Vision__SpecialCar init_value = VISION__SPECIAL_CAR__INIT;
  *message = init_value;
}
size_t vision__special_car__get_packed_size
                     (const Vision__SpecialCar *message)
{
  assert(message->base.descriptor == &vision__special_car__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vision__special_car__pack
                     (const Vision__SpecialCar *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vision__special_car__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vision__special_car__pack_to_buffer
                     (const Vision__SpecialCar *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vision__special_car__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vision__SpecialCar *
       vision__special_car__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vision__SpecialCar *)
     protobuf_c_message_unpack (&vision__special_car__descriptor,
                                allocator, len, data);
}
void   vision__special_car__free_unpacked
                     (Vision__SpecialCar *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vision__special_car__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vision__available_area__init
                     (Vision__AvailableArea         *message)
{
  static const Vision__AvailableArea init_value = VISION__AVAILABLE_AREA__INIT;
  *message = init_value;
}
size_t vision__available_area__get_packed_size
                     (const Vision__AvailableArea *message)
{
  assert(message->base.descriptor == &vision__available_area__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vision__available_area__pack
                     (const Vision__AvailableArea *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vision__available_area__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vision__available_area__pack_to_buffer
                     (const Vision__AvailableArea *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vision__available_area__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vision__AvailableArea *
       vision__available_area__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vision__AvailableArea *)
     protobuf_c_message_unpack (&vision__available_area__descriptor,
                                allocator, len, data);
}
void   vision__available_area__free_unpacked
                     (Vision__AvailableArea *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vision__available_area__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vision__jam_info__init
                     (Vision__JamInfo         *message)
{
  static const Vision__JamInfo init_value = VISION__JAM_INFO__INIT;
  *message = init_value;
}
size_t vision__jam_info__get_packed_size
                     (const Vision__JamInfo *message)
{
  assert(message->base.descriptor == &vision__jam_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vision__jam_info__pack
                     (const Vision__JamInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vision__jam_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vision__jam_info__pack_to_buffer
                     (const Vision__JamInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vision__jam_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vision__JamInfo *
       vision__jam_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vision__JamInfo *)
     protobuf_c_message_unpack (&vision__jam_info__descriptor,
                                allocator, len, data);
}
void   vision__jam_info__free_unpacked
                     (Vision__JamInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vision__jam_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vision__flow_info__init
                     (Vision__FlowInfo         *message)
{
  static const Vision__FlowInfo init_value = VISION__FLOW_INFO__INIT;
  *message = init_value;
}
size_t vision__flow_info__get_packed_size
                     (const Vision__FlowInfo *message)
{
  assert(message->base.descriptor == &vision__flow_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vision__flow_info__pack
                     (const Vision__FlowInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vision__flow_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vision__flow_info__pack_to_buffer
                     (const Vision__FlowInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vision__flow_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vision__FlowInfo *
       vision__flow_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vision__FlowInfo *)
     protobuf_c_message_unpack (&vision__flow_info__descriptor,
                                allocator, len, data);
}
void   vision__flow_info__free_unpacked
                     (Vision__FlowInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vision__flow_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vision__base__init
                     (Vision__Base         *message)
{
  static const Vision__Base init_value = VISION__BASE__INIT;
  *message = init_value;
}
size_t vision__base__get_packed_size
                     (const Vision__Base *message)
{
  assert(message->base.descriptor == &vision__base__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vision__base__pack
                     (const Vision__Base *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vision__base__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vision__base__pack_to_buffer
                     (const Vision__Base *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vision__base__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vision__Base *
       vision__base__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vision__Base *)
     protobuf_c_message_unpack (&vision__base__descriptor,
                                allocator, len, data);
}
void   vision__base__free_unpacked
                     (Vision__Base *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vision__base__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vision__crowd__init
                     (Vision__Crowd         *message)
{
  static const Vision__Crowd init_value = VISION__CROWD__INIT;
  *message = init_value;
}
size_t vision__crowd__get_packed_size
                     (const Vision__Crowd *message)
{
  assert(message->base.descriptor == &vision__crowd__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vision__crowd__pack
                     (const Vision__Crowd *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vision__crowd__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vision__crowd__pack_to_buffer
                     (const Vision__Crowd *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vision__crowd__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vision__Crowd *
       vision__crowd__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vision__Crowd *)
     protobuf_c_message_unpack (&vision__crowd__descriptor,
                                allocator, len, data);
}
void   vision__crowd__free_unpacked
                     (Vision__Crowd *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vision__crowd__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vision__obstacles__init
                     (Vision__Obstacles         *message)
{
  static const Vision__Obstacles init_value = VISION__OBSTACLES__INIT;
  *message = init_value;
}
size_t vision__obstacles__get_packed_size
                     (const Vision__Obstacles *message)
{
  assert(message->base.descriptor == &vision__obstacles__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vision__obstacles__pack
                     (const Vision__Obstacles *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vision__obstacles__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vision__obstacles__pack_to_buffer
                     (const Vision__Obstacles *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vision__obstacles__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vision__Obstacles *
       vision__obstacles__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vision__Obstacles *)
     protobuf_c_message_unpack (&vision__obstacles__descriptor,
                                allocator, len, data);
}
void   vision__obstacles__free_unpacked
                     (Vision__Obstacles *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vision__obstacles__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vision__available_areas__init
                     (Vision__AvailableAreas         *message)
{
  static const Vision__AvailableAreas init_value = VISION__AVAILABLE_AREAS__INIT;
  *message = init_value;
}
size_t vision__available_areas__get_packed_size
                     (const Vision__AvailableAreas *message)
{
  assert(message->base.descriptor == &vision__available_areas__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vision__available_areas__pack
                     (const Vision__AvailableAreas *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vision__available_areas__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vision__available_areas__pack_to_buffer
                     (const Vision__AvailableAreas *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vision__available_areas__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vision__AvailableAreas *
       vision__available_areas__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vision__AvailableAreas *)
     protobuf_c_message_unpack (&vision__available_areas__descriptor,
                                allocator, len, data);
}
void   vision__available_areas__free_unpacked
                     (Vision__AvailableAreas *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vision__available_areas__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vision__illegal_car_warn__init
                     (Vision__IllegalCarWarn         *message)
{
  static const Vision__IllegalCarWarn init_value = VISION__ILLEGAL_CAR_WARN__INIT;
  *message = init_value;
}
size_t vision__illegal_car_warn__get_packed_size
                     (const Vision__IllegalCarWarn *message)
{
  assert(message->base.descriptor == &vision__illegal_car_warn__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vision__illegal_car_warn__pack
                     (const Vision__IllegalCarWarn *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vision__illegal_car_warn__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vision__illegal_car_warn__pack_to_buffer
                     (const Vision__IllegalCarWarn *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vision__illegal_car_warn__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vision__IllegalCarWarn *
       vision__illegal_car_warn__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vision__IllegalCarWarn *)
     protobuf_c_message_unpack (&vision__illegal_car_warn__descriptor,
                                allocator, len, data);
}
void   vision__illegal_car_warn__free_unpacked
                     (Vision__IllegalCarWarn *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vision__illegal_car_warn__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vision__visibility__init
                     (Vision__Visibility         *message)
{
  static const Vision__Visibility init_value = VISION__VISIBILITY__INIT;
  *message = init_value;
}
size_t vision__visibility__get_packed_size
                     (const Vision__Visibility *message)
{
  assert(message->base.descriptor == &vision__visibility__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vision__visibility__pack
                     (const Vision__Visibility *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vision__visibility__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vision__visibility__pack_to_buffer
                     (const Vision__Visibility *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vision__visibility__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vision__Visibility *
       vision__visibility__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vision__Visibility *)
     protobuf_c_message_unpack (&vision__visibility__descriptor,
                                allocator, len, data);
}
void   vision__visibility__free_unpacked
                     (Vision__Visibility *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vision__visibility__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vision__smoke_warn__init
                     (Vision__SmokeWarn         *message)
{
  static const Vision__SmokeWarn init_value = VISION__SMOKE_WARN__INIT;
  *message = init_value;
}
size_t vision__smoke_warn__get_packed_size
                     (const Vision__SmokeWarn *message)
{
  assert(message->base.descriptor == &vision__smoke_warn__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vision__smoke_warn__pack
                     (const Vision__SmokeWarn *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vision__smoke_warn__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vision__smoke_warn__pack_to_buffer
                     (const Vision__SmokeWarn *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vision__smoke_warn__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vision__SmokeWarn *
       vision__smoke_warn__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vision__SmokeWarn *)
     protobuf_c_message_unpack (&vision__smoke_warn__descriptor,
                                allocator, len, data);
}
void   vision__smoke_warn__free_unpacked
                     (Vision__SmokeWarn *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vision__smoke_warn__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vision__timestamp__init
                     (Vision__Timestamp         *message)
{
  static const Vision__Timestamp init_value = VISION__TIMESTAMP__INIT;
  *message = init_value;
}
size_t vision__timestamp__get_packed_size
                     (const Vision__Timestamp *message)
{
  assert(message->base.descriptor == &vision__timestamp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vision__timestamp__pack
                     (const Vision__Timestamp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vision__timestamp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vision__timestamp__pack_to_buffer
                     (const Vision__Timestamp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vision__timestamp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vision__Timestamp *
       vision__timestamp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vision__Timestamp *)
     protobuf_c_message_unpack (&vision__timestamp__descriptor,
                                allocator, len, data);
}
void   vision__timestamp__free_unpacked
                     (Vision__Timestamp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vision__timestamp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vision__detectobject__init
                     (Vision__Detectobject         *message)
{
  static const Vision__Detectobject init_value = VISION__DETECTOBJECT__INIT;
  *message = init_value;
}
size_t vision__detectobject__get_packed_size
                     (const Vision__Detectobject *message)
{
  assert(message->base.descriptor == &vision__detectobject__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vision__detectobject__pack
                     (const Vision__Detectobject *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vision__detectobject__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vision__detectobject__pack_to_buffer
                     (const Vision__Detectobject *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vision__detectobject__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vision__Detectobject *
       vision__detectobject__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vision__Detectobject *)
     protobuf_c_message_unpack (&vision__detectobject__descriptor,
                                allocator, len, data);
}
void   vision__detectobject__free_unpacked
                     (Vision__Detectobject *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vision__detectobject__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vision__detectobjects__init
                     (Vision__Detectobjects         *message)
{
  static const Vision__Detectobjects init_value = VISION__DETECTOBJECTS__INIT;
  *message = init_value;
}
size_t vision__detectobjects__get_packed_size
                     (const Vision__Detectobjects *message)
{
  assert(message->base.descriptor == &vision__detectobjects__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vision__detectobjects__pack
                     (const Vision__Detectobjects *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vision__detectobjects__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vision__detectobjects__pack_to_buffer
                     (const Vision__Detectobjects *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vision__detectobjects__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vision__Detectobjects *
       vision__detectobjects__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vision__Detectobjects *)
     protobuf_c_message_unpack (&vision__detectobjects__descriptor,
                                allocator, len, data);
}
void   vision__detectobjects__free_unpacked
                     (Vision__Detectobjects *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vision__detectobjects__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vision__traffic_jam__init
                     (Vision__TrafficJam         *message)
{
  static const Vision__TrafficJam init_value = VISION__TRAFFIC_JAM__INIT;
  *message = init_value;
}
size_t vision__traffic_jam__get_packed_size
                     (const Vision__TrafficJam *message)
{
  assert(message->base.descriptor == &vision__traffic_jam__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vision__traffic_jam__pack
                     (const Vision__TrafficJam *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vision__traffic_jam__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vision__traffic_jam__pack_to_buffer
                     (const Vision__TrafficJam *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vision__traffic_jam__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vision__TrafficJam *
       vision__traffic_jam__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vision__TrafficJam *)
     protobuf_c_message_unpack (&vision__traffic_jam__descriptor,
                                allocator, len, data);
}
void   vision__traffic_jam__free_unpacked
                     (Vision__TrafficJam *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vision__traffic_jam__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vision__traffic_flow__init
                     (Vision__TrafficFlow         *message)
{
  static const Vision__TrafficFlow init_value = VISION__TRAFFIC_FLOW__INIT;
  *message = init_value;
}
size_t vision__traffic_flow__get_packed_size
                     (const Vision__TrafficFlow *message)
{
  assert(message->base.descriptor == &vision__traffic_flow__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vision__traffic_flow__pack
                     (const Vision__TrafficFlow *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vision__traffic_flow__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vision__traffic_flow__pack_to_buffer
                     (const Vision__TrafficFlow *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vision__traffic_flow__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vision__TrafficFlow *
       vision__traffic_flow__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vision__TrafficFlow *)
     protobuf_c_message_unpack (&vision__traffic_flow__descriptor,
                                allocator, len, data);
}
void   vision__traffic_flow__free_unpacked
                     (Vision__TrafficFlow *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vision__traffic_flow__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vision__ice_warn__init
                     (Vision__IceWarn         *message)
{
  static const Vision__IceWarn init_value = VISION__ICE_WARN__INIT;
  *message = init_value;
}
size_t vision__ice_warn__get_packed_size
                     (const Vision__IceWarn *message)
{
  assert(message->base.descriptor == &vision__ice_warn__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vision__ice_warn__pack
                     (const Vision__IceWarn *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vision__ice_warn__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vision__ice_warn__pack_to_buffer
                     (const Vision__IceWarn *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vision__ice_warn__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vision__IceWarn *
       vision__ice_warn__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vision__IceWarn *)
     protobuf_c_message_unpack (&vision__ice_warn__descriptor,
                                allocator, len, data);
}
void   vision__ice_warn__free_unpacked
                     (Vision__IceWarn *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vision__ice_warn__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vision__lane_ware__init
                     (Vision__LaneWare         *message)
{
  static const Vision__LaneWare init_value = VISION__LANE_WARE__INIT;
  *message = init_value;
}
size_t vision__lane_ware__get_packed_size
                     (const Vision__LaneWare *message)
{
  assert(message->base.descriptor == &vision__lane_ware__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vision__lane_ware__pack
                     (const Vision__LaneWare *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vision__lane_ware__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vision__lane_ware__pack_to_buffer
                     (const Vision__LaneWare *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vision__lane_ware__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vision__LaneWare *
       vision__lane_ware__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vision__LaneWare *)
     protobuf_c_message_unpack (&vision__lane_ware__descriptor,
                                allocator, len, data);
}
void   vision__lane_ware__free_unpacked
                     (Vision__LaneWare *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vision__lane_ware__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vision__special_car_msg__init
                     (Vision__SpecialCarMsg         *message)
{
  static const Vision__SpecialCarMsg init_value = VISION__SPECIAL_CAR_MSG__INIT;
  *message = init_value;
}
size_t vision__special_car_msg__get_packed_size
                     (const Vision__SpecialCarMsg *message)
{
  assert(message->base.descriptor == &vision__special_car_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vision__special_car_msg__pack
                     (const Vision__SpecialCarMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vision__special_car_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vision__special_car_msg__pack_to_buffer
                     (const Vision__SpecialCarMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vision__special_car_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Vision__SpecialCarMsg *
       vision__special_car_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Vision__SpecialCarMsg *)
     protobuf_c_message_unpack (&vision__special_car_msg__descriptor,
                                allocator, len, data);
}
void   vision__special_car_msg__free_unpacked
                     (Vision__SpecialCarMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vision__special_car_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor vision__data_time__field_descriptors[2] =
{
  {
    "sec",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Vision__DataTime, sec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "usec",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Vision__DataTime, usec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vision__data_time__field_indices_by_name[] = {
  0,   /* field[0] = sec */
  1,   /* field[1] = usec */
};
static const ProtobufCIntRange vision__data_time__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor vision__data_time__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vision.data_time",
  "DataTime",
  "Vision__DataTime",
  "vision",
  sizeof(Vision__DataTime),
  2,
  vision__data_time__field_descriptors,
  vision__data_time__field_indices_by_name,
  1,  vision__data_time__number_ranges,
  (ProtobufCMessageInit) vision__data_time__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vision__pedestrian__field_descriptors[12] =
{
  {
    "object_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__Pedestrian, object_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "object_type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Vision__Pedestrian, object_type),
    &vision__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lng",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__Pedestrian, lng),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lat",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__Pedestrian, lat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "camera",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__Pedestrian, camera),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "if_at_lane",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vision__Pedestrian, has_if_at_lane),
    offsetof(Vision__Pedestrian, if_at_lane),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lane_id",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vision__Pedestrian, has_lane_id),
    offsetof(Vision__Pedestrian, lane_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "heading",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vision__Pedestrian, has_heading),
    offsetof(Vision__Pedestrian, heading),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "approach_judge",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vision__Pedestrian, has_approach_judge),
    offsetof(Vision__Pedestrian, approach_judge),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speed",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vision__Pedestrian, has_speed),
    offsetof(Vision__Pedestrian, speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "people_heading",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vision__Pedestrian, has_people_heading),
    offsetof(Vision__Pedestrian, people_heading),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lane_type",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vision__Pedestrian, has_lane_type),
    offsetof(Vision__Pedestrian, lane_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vision__pedestrian__field_indices_by_name[] = {
  8,   /* field[8] = approach_judge */
  4,   /* field[4] = camera */
  7,   /* field[7] = heading */
  5,   /* field[5] = if_at_lane */
  6,   /* field[6] = lane_id */
  11,   /* field[11] = lane_type */
  3,   /* field[3] = lat */
  2,   /* field[2] = lng */
  0,   /* field[0] = object_id */
  1,   /* field[1] = object_type */
  10,   /* field[10] = people_heading */
  9,   /* field[9] = speed */
};
static const ProtobufCIntRange vision__pedestrian__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor vision__pedestrian__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vision.Pedestrian",
  "Pedestrian",
  "Vision__Pedestrian",
  "vision",
  sizeof(Vision__Pedestrian),
  12,
  vision__pedestrian__field_descriptors,
  vision__pedestrian__field_indices_by_name,
  1,  vision__pedestrian__number_ranges,
  (ProtobufCMessageInit) vision__pedestrian__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vision__obstacle__field_descriptors[10] =
{
  {
    "object_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__Obstacle, object_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lng",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__Obstacle, lng),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lat",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__Obstacle, lat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "camera",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__Obstacle, camera),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "if_at_lane",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vision__Obstacle, has_if_at_lane),
    offsetof(Vision__Obstacle, if_at_lane),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lane_id",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vision__Obstacle, has_lane_id),
    offsetof(Vision__Obstacle, lane_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "heading",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vision__Obstacle, has_heading),
    offsetof(Vision__Obstacle, heading),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vision__Obstacle, has_length),
    offsetof(Vision__Obstacle, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "width",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vision__Obstacle, has_width),
    offsetof(Vision__Obstacle, width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vision__Obstacle, has_height),
    offsetof(Vision__Obstacle, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vision__obstacle__field_indices_by_name[] = {
  3,   /* field[3] = camera */
  6,   /* field[6] = heading */
  9,   /* field[9] = height */
  4,   /* field[4] = if_at_lane */
  5,   /* field[5] = lane_id */
  2,   /* field[2] = lat */
  7,   /* field[7] = length */
  1,   /* field[1] = lng */
  0,   /* field[0] = object_id */
  8,   /* field[8] = width */
};
static const ProtobufCIntRange vision__obstacle__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor vision__obstacle__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vision.Obstacle",
  "Obstacle",
  "Vision__Obstacle",
  "vision",
  sizeof(Vision__Obstacle),
  10,
  vision__obstacle__field_descriptors,
  vision__obstacle__field_indices_by_name,
  1,  vision__obstacle__number_ranges,
  (ProtobufCMessageInit) vision__obstacle__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vision__abnormal_car__field_descriptors[6] =
{
  {
    "object_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__AbnormalCar, object_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lng",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__AbnormalCar, lng),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lat",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__AbnormalCar, lat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lane_id",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vision__AbnormalCar, has_lane_id),
    offsetof(Vision__AbnormalCar, lane_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "camera",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vision__AbnormalCar, has_camera),
    offsetof(Vision__AbnormalCar, camera),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "abnormal_type",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Vision__AbnormalCar, has_abnormal_type),
    offsetof(Vision__AbnormalCar, abnormal_type),
    &vision__abnormaltype__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vision__abnormal_car__field_indices_by_name[] = {
  5,   /* field[5] = abnormal_type */
  4,   /* field[4] = camera */
  3,   /* field[3] = lane_id */
  2,   /* field[2] = lat */
  1,   /* field[1] = lng */
  0,   /* field[0] = object_id */
};
static const ProtobufCIntRange vision__abnormal_car__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor vision__abnormal_car__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vision.AbnormalCar",
  "AbnormalCar",
  "Vision__AbnormalCar",
  "vision",
  sizeof(Vision__AbnormalCar),
  6,
  vision__abnormal_car__field_descriptors,
  vision__abnormal_car__field_indices_by_name,
  1,  vision__abnormal_car__number_ranges,
  (ProtobufCMessageInit) vision__abnormal_car__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue vision__special_car__specialtype__enum_values_by_number[4] =
{
  { "NORMAL", "VISION__SPECIAL_CAR__SPECIALTYPE__NORMAL", 0 },
  { "AMBULANCE", "VISION__SPECIAL_CAR__SPECIALTYPE__AMBULANCE", 1 },
  { "DANGERCAR", "VISION__SPECIAL_CAR__SPECIALTYPE__DANGERCAR", 2 },
  { "FIREENGINE", "VISION__SPECIAL_CAR__SPECIALTYPE__FIREENGINE", 3 },
};
static const ProtobufCIntRange vision__special_car__specialtype__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex vision__special_car__specialtype__enum_values_by_name[4] =
{
  { "AMBULANCE", 1 },
  { "DANGERCAR", 2 },
  { "FIREENGINE", 3 },
  { "NORMAL", 0 },
};
const ProtobufCEnumDescriptor vision__special_car__specialtype__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "vision.SpecialCar.SPECIALTYPE",
  "SPECIALTYPE",
  "Vision__SpecialCar__SPECIALTYPE",
  "vision",
  4,
  vision__special_car__specialtype__enum_values_by_number,
  4,
  vision__special_car__specialtype__enum_values_by_name,
  1,
  vision__special_car__specialtype__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor vision__special_car__field_descriptors[8] =
{
  {
    "object_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__SpecialCar, object_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "special_type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Vision__SpecialCar, special_type),
    &vision__special_car__specialtype__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lng",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__SpecialCar, lng),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lat",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__SpecialCar, lat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "camera",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__SpecialCar, camera),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lane_id",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vision__SpecialCar, has_lane_id),
    offsetof(Vision__SpecialCar, lane_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "heading",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vision__SpecialCar, has_heading),
    offsetof(Vision__SpecialCar, heading),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lane_type",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vision__SpecialCar, has_lane_type),
    offsetof(Vision__SpecialCar, lane_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vision__special_car__field_indices_by_name[] = {
  4,   /* field[4] = camera */
  6,   /* field[6] = heading */
  5,   /* field[5] = lane_id */
  7,   /* field[7] = lane_type */
  3,   /* field[3] = lat */
  2,   /* field[2] = lng */
  0,   /* field[0] = object_id */
  1,   /* field[1] = special_type */
};
static const ProtobufCIntRange vision__special_car__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor vision__special_car__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vision.SpecialCar",
  "SpecialCar",
  "Vision__SpecialCar",
  "vision",
  sizeof(Vision__SpecialCar),
  8,
  vision__special_car__field_descriptors,
  vision__special_car__field_indices_by_name,
  1,  vision__special_car__number_ranges,
  (ProtobufCMessageInit) vision__special_car__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vision__available_area__field_descriptors[12] =
{
  {
    "object_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__AvailableArea, object_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lng1",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__AvailableArea, lng1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lat1",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__AvailableArea, lat1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lng2",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__AvailableArea, lng2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lat2",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__AvailableArea, lat2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lng3",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__AvailableArea, lng3),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lat3",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__AvailableArea, lat3),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lng4",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__AvailableArea, lng4),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lat4",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__AvailableArea, lat4),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "camera",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__AvailableArea, camera),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lane_id",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vision__AvailableArea, has_lane_id),
    offsetof(Vision__AvailableArea, lane_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "heading",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vision__AvailableArea, has_heading),
    offsetof(Vision__AvailableArea, heading),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vision__available_area__field_indices_by_name[] = {
  9,   /* field[9] = camera */
  11,   /* field[11] = heading */
  10,   /* field[10] = lane_id */
  2,   /* field[2] = lat1 */
  4,   /* field[4] = lat2 */
  6,   /* field[6] = lat3 */
  8,   /* field[8] = lat4 */
  1,   /* field[1] = lng1 */
  3,   /* field[3] = lng2 */
  5,   /* field[5] = lng3 */
  7,   /* field[7] = lng4 */
  0,   /* field[0] = object_id */
};
static const ProtobufCIntRange vision__available_area__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor vision__available_area__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vision.AvailableArea",
  "AvailableArea",
  "Vision__AvailableArea",
  "vision",
  sizeof(Vision__AvailableArea),
  12,
  vision__available_area__field_descriptors,
  vision__available_area__field_indices_by_name,
  1,  vision__available_area__number_ranges,
  (ProtobufCMessageInit) vision__available_area__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vision__jam_info__field_descriptors[5] =
{
  {
    "vehicle_num",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Vision__JamInfo, vehicle_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vehicle_avg_speed",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Vision__JamInfo, vehicle_avg_speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "road_yaw",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Vision__JamInfo, road_yaw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vehicle_flow",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vision__JamInfo, n_vehicle_flow),
    offsetof(Vision__JamInfo, vehicle_flow),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lane_id",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vision__JamInfo, has_lane_id),
    offsetof(Vision__JamInfo, lane_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vision__jam_info__field_indices_by_name[] = {
  4,   /* field[4] = lane_id */
  2,   /* field[2] = road_yaw */
  1,   /* field[1] = vehicle_avg_speed */
  3,   /* field[3] = vehicle_flow */
  0,   /* field[0] = vehicle_num */
};
static const ProtobufCIntRange vision__jam_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor vision__jam_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vision.JamInfo",
  "JamInfo",
  "Vision__JamInfo",
  "vision",
  sizeof(Vision__JamInfo),
  5,
  vision__jam_info__field_descriptors,
  vision__jam_info__field_indices_by_name,
  1,  vision__jam_info__number_ranges,
  (ProtobufCMessageInit) vision__jam_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue vision__flow_info__traffic_sig__enum_values_by_number[3] =
{
  { "UNKNOWN", "VISION__FLOW_INFO__TRAFFIC_SIG__UNKNOWN", 0 },
  { "Y2G", "VISION__FLOW_INFO__TRAFFIC_SIG__Y2G", 1 },
  { "OVER", "VISION__FLOW_INFO__TRAFFIC_SIG__OVER", 2 },
};
static const ProtobufCIntRange vision__flow_info__traffic_sig__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex vision__flow_info__traffic_sig__enum_values_by_name[3] =
{
  { "OVER", 2 },
  { "UNKNOWN", 0 },
  { "Y2G", 1 },
};
const ProtobufCEnumDescriptor vision__flow_info__traffic_sig__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "vision.FlowInfo.TrafficSig",
  "TrafficSig",
  "Vision__FlowInfo__TrafficSig",
  "vision",
  3,
  vision__flow_info__traffic_sig__enum_values_by_number,
  3,
  vision__flow_info__traffic_sig__enum_values_by_name,
  1,
  vision__flow_info__traffic_sig__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor vision__flow_info__field_descriptors[4] =
{
  {
    "camera",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vision__FlowInfo, has_camera),
    offsetof(Vision__FlowInfo, camera),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vehicle_num",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Vision__FlowInfo, n_vehicle_num),
    offsetof(Vision__FlowInfo, vehicle_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pass_num",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Vision__FlowInfo, n_pass_num),
    offsetof(Vision__FlowInfo, pass_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signal",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Vision__FlowInfo, has_signal),
    offsetof(Vision__FlowInfo, signal),
    &vision__flow_info__traffic_sig__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vision__flow_info__field_indices_by_name[] = {
  0,   /* field[0] = camera */
  2,   /* field[2] = pass_num */
  3,   /* field[3] = signal */
  1,   /* field[1] = vehicle_num */
};
static const ProtobufCIntRange vision__flow_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor vision__flow_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vision.FlowInfo",
  "FlowInfo",
  "Vision__FlowInfo",
  "vision",
  sizeof(Vision__FlowInfo),
  4,
  vision__flow_info__field_descriptors,
  vision__flow_info__field_indices_by_name,
  1,  vision__flow_info__number_ranges,
  (ProtobufCMessageInit) vision__flow_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vision__base__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Vision__Base, id),
    &vision__id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vision__base__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange vision__base__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor vision__base__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vision.Base",
  "Base",
  "Vision__Base",
  "vision",
  sizeof(Vision__Base),
  1,
  vision__base__field_descriptors,
  vision__base__field_indices_by_name,
  1,  vision__base__number_ranges,
  (ProtobufCMessageInit) vision__base__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vision__crowd__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Vision__Crowd, id),
    &vision__id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pedestrian",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Vision__Crowd, n_pedestrian),
    offsetof(Vision__Crowd, pedestrian),
    &vision__pedestrian__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Vision__Crowd, time),
    &vision__data_time__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vision__crowd__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = pedestrian */
  2,   /* field[2] = time */
};
static const ProtobufCIntRange vision__crowd__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor vision__crowd__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vision.Crowd",
  "Crowd",
  "Vision__Crowd",
  "vision",
  sizeof(Vision__Crowd),
  3,
  vision__crowd__field_descriptors,
  vision__crowd__field_indices_by_name,
  1,  vision__crowd__number_ranges,
  (ProtobufCMessageInit) vision__crowd__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vision__obstacles__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Vision__Obstacles, id),
    &vision__id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "array",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Vision__Obstacles, n_array),
    offsetof(Vision__Obstacles, array),
    &vision__obstacle__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Vision__Obstacles, time),
    &vision__data_time__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vision__obstacles__field_indices_by_name[] = {
  1,   /* field[1] = array */
  0,   /* field[0] = id */
  2,   /* field[2] = time */
};
static const ProtobufCIntRange vision__obstacles__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor vision__obstacles__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vision.Obstacles",
  "Obstacles",
  "Vision__Obstacles",
  "vision",
  sizeof(Vision__Obstacles),
  3,
  vision__obstacles__field_descriptors,
  vision__obstacles__field_indices_by_name,
  1,  vision__obstacles__number_ranges,
  (ProtobufCMessageInit) vision__obstacles__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vision__available_areas__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Vision__AvailableAreas, id),
    &vision__id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "area",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Vision__AvailableAreas, n_area),
    offsetof(Vision__AvailableAreas, area),
    &vision__available_area__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Vision__AvailableAreas, time),
    &vision__data_time__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vision__available_areas__field_indices_by_name[] = {
  1,   /* field[1] = area */
  0,   /* field[0] = id */
  2,   /* field[2] = time */
};
static const ProtobufCIntRange vision__available_areas__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor vision__available_areas__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vision.AvailableAreas",
  "AvailableAreas",
  "Vision__AvailableAreas",
  "vision",
  sizeof(Vision__AvailableAreas),
  3,
  vision__available_areas__field_descriptors,
  vision__available_areas__field_indices_by_name,
  1,  vision__available_areas__number_ranges,
  (ProtobufCMessageInit) vision__available_areas__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vision__illegal_car_warn__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Vision__IllegalCarWarn, id),
    &vision__id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "array",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Vision__IllegalCarWarn, n_array),
    offsetof(Vision__IllegalCarWarn, array),
    &vision__abnormal_car__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Vision__IllegalCarWarn, time),
    &vision__data_time__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vision__illegal_car_warn__field_indices_by_name[] = {
  1,   /* field[1] = array */
  0,   /* field[0] = id */
  2,   /* field[2] = time */
};
static const ProtobufCIntRange vision__illegal_car_warn__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor vision__illegal_car_warn__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vision.IllegalCarWarn",
  "IllegalCarWarn",
  "Vision__IllegalCarWarn",
  "vision",
  sizeof(Vision__IllegalCarWarn),
  3,
  vision__illegal_car_warn__field_descriptors,
  vision__illegal_car_warn__field_indices_by_name,
  1,  vision__illegal_car_warn__number_ranges,
  (ProtobufCMessageInit) vision__illegal_car_warn__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vision__visibility__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Vision__Visibility, id),
    &vision__id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "distance",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Vision__Visibility, distance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "level",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__Visibility, level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vision__visibility__field_indices_by_name[] = {
  1,   /* field[1] = distance */
  0,   /* field[0] = id */
  2,   /* field[2] = level */
};
static const ProtobufCIntRange vision__visibility__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor vision__visibility__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vision.Visibility",
  "Visibility",
  "Vision__Visibility",
  "vision",
  sizeof(Vision__Visibility),
  3,
  vision__visibility__field_descriptors,
  vision__visibility__field_indices_by_name,
  1,  vision__visibility__number_ranges,
  (ProtobufCMessageInit) vision__visibility__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vision__smoke_warn__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Vision__SmokeWarn, id),
    &vision__id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "warn",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Vision__SmokeWarn, warn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vision__smoke_warn__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = warn */
};
static const ProtobufCIntRange vision__smoke_warn__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor vision__smoke_warn__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vision.SmokeWarn",
  "SmokeWarn",
  "Vision__SmokeWarn",
  "vision",
  sizeof(Vision__SmokeWarn),
  2,
  vision__smoke_warn__field_descriptors,
  vision__smoke_warn__field_indices_by_name,
  1,  vision__smoke_warn__number_ranges,
  (ProtobufCMessageInit) vision__smoke_warn__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vision__timestamp__field_descriptors[2] =
{
  {
    "seconds",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Vision__Timestamp, seconds),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nanos",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__Timestamp, nanos),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vision__timestamp__field_indices_by_name[] = {
  1,   /* field[1] = nanos */
  0,   /* field[0] = seconds */
};
static const ProtobufCIntRange vision__timestamp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor vision__timestamp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vision.Timestamp",
  "Timestamp",
  "Vision__Timestamp",
  "vision",
  sizeof(Vision__Timestamp),
  2,
  vision__timestamp__field_descriptors,
  vision__timestamp__field_indices_by_name,
  1,  vision__timestamp__number_ranges,
  (ProtobufCMessageInit) vision__timestamp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vision__detectobject__field_descriptors[10] =
{
  {
    "object_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__Detectobject, object_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "object_type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Vision__Detectobject, object_type),
    &vision__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "longitudinalX",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__Detectobject, longitudinalx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lateralY",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__Detectobject, lateraly),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "velocity",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__Detectobject, velocity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "camera",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__Detectobject, camera),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "if_at_lane",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vision__Detectobject, has_if_at_lane),
    offsetof(Vision__Detectobject, if_at_lane),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lane_id",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vision__Detectobject, has_lane_id),
    offsetof(Vision__Detectobject, lane_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "heading",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vision__Detectobject, has_heading),
    offsetof(Vision__Detectobject, heading),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lane_type",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vision__Detectobject, has_lane_type),
    offsetof(Vision__Detectobject, lane_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vision__detectobject__field_indices_by_name[] = {
  5,   /* field[5] = camera */
  8,   /* field[8] = heading */
  6,   /* field[6] = if_at_lane */
  7,   /* field[7] = lane_id */
  9,   /* field[9] = lane_type */
  3,   /* field[3] = lateralY */
  2,   /* field[2] = longitudinalX */
  0,   /* field[0] = object_id */
  1,   /* field[1] = object_type */
  4,   /* field[4] = velocity */
};
static const ProtobufCIntRange vision__detectobject__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor vision__detectobject__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vision.Detectobject",
  "Detectobject",
  "Vision__Detectobject",
  "vision",
  sizeof(Vision__Detectobject),
  10,
  vision__detectobject__field_descriptors,
  vision__detectobject__field_indices_by_name,
  1,  vision__detectobject__number_ranges,
  (ProtobufCMessageInit) vision__detectobject__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vision__detectobjects__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Vision__Detectobjects, id),
    &vision__id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "object",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Vision__Detectobjects, n_object),
    offsetof(Vision__Detectobjects, object),
    &vision__detectobject__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Vision__Detectobjects, time),
    &vision__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vision__detectobjects__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = object */
  2,   /* field[2] = time */
};
static const ProtobufCIntRange vision__detectobjects__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor vision__detectobjects__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vision.Detectobjects",
  "Detectobjects",
  "Vision__Detectobjects",
  "vision",
  sizeof(Vision__Detectobjects),
  3,
  vision__detectobjects__field_descriptors,
  vision__detectobjects__field_indices_by_name,
  1,  vision__detectobjects__number_ranges,
  (ProtobufCMessageInit) vision__detectobjects__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vision__traffic_jam__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Vision__TrafficJam, id),
    &vision__id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "jam",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Vision__TrafficJam, n_jam),
    offsetof(Vision__TrafficJam, jam),
    &vision__jam_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Vision__TrafficJam, time),
    &vision__data_time__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vision__traffic_jam__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = jam */
  2,   /* field[2] = time */
};
static const ProtobufCIntRange vision__traffic_jam__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor vision__traffic_jam__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vision.TrafficJam",
  "TrafficJam",
  "Vision__TrafficJam",
  "vision",
  sizeof(Vision__TrafficJam),
  3,
  vision__traffic_jam__field_descriptors,
  vision__traffic_jam__field_indices_by_name,
  1,  vision__traffic_jam__number_ranges,
  (ProtobufCMessageInit) vision__traffic_jam__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vision__traffic_flow__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Vision__TrafficFlow, id),
    &vision__id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flow",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Vision__TrafficFlow, n_flow),
    offsetof(Vision__TrafficFlow, flow),
    &vision__flow_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Vision__TrafficFlow, time),
    &vision__data_time__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vision__traffic_flow__field_indices_by_name[] = {
  1,   /* field[1] = flow */
  0,   /* field[0] = id */
  2,   /* field[2] = time */
};
static const ProtobufCIntRange vision__traffic_flow__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor vision__traffic_flow__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vision.TrafficFlow",
  "TrafficFlow",
  "Vision__TrafficFlow",
  "vision",
  sizeof(Vision__TrafficFlow),
  3,
  vision__traffic_flow__field_descriptors,
  vision__traffic_flow__field_indices_by_name,
  1,  vision__traffic_flow__number_ranges,
  (ProtobufCMessageInit) vision__traffic_flow__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vision__ice_warn__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Vision__IceWarn, id),
    &vision__id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "warn",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Vision__IceWarn, warn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vision__ice_warn__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = warn */
};
static const ProtobufCIntRange vision__ice_warn__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor vision__ice_warn__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vision.IceWarn",
  "IceWarn",
  "Vision__IceWarn",
  "vision",
  sizeof(Vision__IceWarn),
  2,
  vision__ice_warn__field_descriptors,
  vision__ice_warn__field_indices_by_name,
  1,  vision__ice_warn__number_ranges,
  (ProtobufCMessageInit) vision__ice_warn__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue vision__lane_ware__waretype__enum_values_by_number[4] =
{
  { "DEFAULT", "VISION__LANE_WARE__WARETYPE__DEFAULT", 0 },
  { "FULLLINE", "VISION__LANE_WARE__WARETYPE__FULLLINE", 1 },
  { "DOTTEDLINE", "VISION__LANE_WARE__WARETYPE__DOTTEDLINE", 2 },
  { "DOUBLEYELLOWLINE", "VISION__LANE_WARE__WARETYPE__DOUBLEYELLOWLINE", 3 },
};
static const ProtobufCIntRange vision__lane_ware__waretype__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex vision__lane_ware__waretype__enum_values_by_name[4] =
{
  { "DEFAULT", 0 },
  { "DOTTEDLINE", 2 },
  { "DOUBLEYELLOWLINE", 3 },
  { "FULLLINE", 1 },
};
const ProtobufCEnumDescriptor vision__lane_ware__waretype__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "vision.LaneWare.WARETYPE",
  "WARETYPE",
  "Vision__LaneWare__WARETYPE",
  "vision",
  4,
  vision__lane_ware__waretype__enum_values_by_number,
  4,
  vision__lane_ware__waretype__enum_values_by_name,
  1,
  vision__lane_ware__waretype__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor vision__lane_ware__field_descriptors[7] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Vision__LaneWare, id),
    &vision__id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ware_type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Vision__LaneWare, ware_type),
    &vision__lane_ware__waretype__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lng1",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__LaneWare, lng1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lat1",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__LaneWare, lat1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lng2",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__LaneWare, lng2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lat2",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Vision__LaneWare, lat2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "heading",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Vision__LaneWare, has_heading),
    offsetof(Vision__LaneWare, heading),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vision__lane_ware__field_indices_by_name[] = {
  6,   /* field[6] = heading */
  0,   /* field[0] = id */
  3,   /* field[3] = lat1 */
  5,   /* field[5] = lat2 */
  2,   /* field[2] = lng1 */
  4,   /* field[4] = lng2 */
  1,   /* field[1] = ware_type */
};
static const ProtobufCIntRange vision__lane_ware__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor vision__lane_ware__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vision.LaneWare",
  "LaneWare",
  "Vision__LaneWare",
  "vision",
  sizeof(Vision__LaneWare),
  7,
  vision__lane_ware__field_descriptors,
  vision__lane_ware__field_indices_by_name,
  1,  vision__lane_ware__number_ranges,
  (ProtobufCMessageInit) vision__lane_ware__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vision__special_car_msg__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Vision__SpecialCarMsg, id),
    &vision__id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "array",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Vision__SpecialCarMsg, n_array),
    offsetof(Vision__SpecialCarMsg, array),
    &vision__special_car__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Vision__SpecialCarMsg, time),
    &vision__data_time__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vision__special_car_msg__field_indices_by_name[] = {
  1,   /* field[1] = array */
  0,   /* field[0] = id */
  2,   /* field[2] = time */
};
static const ProtobufCIntRange vision__special_car_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor vision__special_car_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "vision.SpecialCarMsg",
  "SpecialCarMsg",
  "Vision__SpecialCarMsg",
  "vision",
  sizeof(Vision__SpecialCarMsg),
  3,
  vision__special_car_msg__field_descriptors,
  vision__special_car_msg__field_indices_by_name,
  1,  vision__special_car_msg__number_ranges,
  (ProtobufCMessageInit) vision__special_car_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue vision__id__enum_values_by_number[18] =
{
  { "DEFAULT", "VISION__ID__DEFAULT", 0 },
  { "PEDESTRIAN_D", "VISION__ID__PEDESTRIAN_D", 1 },
  { "ILLEGAL_V1", "VISION__ID__ILLEGAL_V1", 2 },
  { "VISIBILITY", "VISION__ID__VISIBILITY", 3 },
  { "AVAILABLE_AREA", "VISION__ID__AVAILABLE_AREA", 4 },
  { "ABNORMAL_CAR", "VISION__ID__ABNORMAL_CAR", 5 },
  { "ILLEGAL_V2", "VISION__ID__ILLEGAL_V2", 6 },
  { "TRAFFIC_STATUS", "VISION__ID__TRAFFIC_STATUS", 7 },
  { "BACKWARD_DRIVING", "VISION__ID__BACKWARD_DRIVING", 8 },
  { "ROAD_DANGER", "VISION__ID__ROAD_DANGER", 9 },
  { "FIRE_SMOKE", "VISION__ID__FIRE_SMOKE", 10 },
  { "DETECTOBJECTS", "VISION__ID__DETECTOBJECTS", 11 },
  { "TRAFFIC_JAM", "VISION__ID__TRAFFIC_JAM", 12 },
  { "TRAFFIC_FLOW", "VISION__ID__TRAFFIC_FLOW", 13 },
  { "SPECIALCAR", "VISION__ID__SPECIALCAR", 14 },
  { "ACCIDENT", "VISION__ID__ACCIDENT", 15 },
  { "ICEWARN", "VISION__ID__ICEWARN", 16 },
  { "LANE_WARE", "VISION__ID__LANE_WARE", 17 },
};
static const ProtobufCIntRange vision__id__value_ranges[] = {
{0, 0},{0, 18}
};
static const ProtobufCEnumValueIndex vision__id__enum_values_by_name[18] =
{
  { "ABNORMAL_CAR", 5 },
  { "ACCIDENT", 15 },
  { "AVAILABLE_AREA", 4 },
  { "BACKWARD_DRIVING", 8 },
  { "DEFAULT", 0 },
  { "DETECTOBJECTS", 11 },
  { "FIRE_SMOKE", 10 },
  { "ICEWARN", 16 },
  { "ILLEGAL_V1", 2 },
  { "ILLEGAL_V2", 6 },
  { "LANE_WARE", 17 },
  { "PEDESTRIAN_D", 1 },
  { "ROAD_DANGER", 9 },
  { "SPECIALCAR", 14 },
  { "TRAFFIC_FLOW", 13 },
  { "TRAFFIC_JAM", 12 },
  { "TRAFFIC_STATUS", 7 },
  { "VISIBILITY", 3 },
};
const ProtobufCEnumDescriptor vision__id__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "vision.ID",
  "ID",
  "Vision__ID",
  "vision",
  18,
  vision__id__enum_values_by_number,
  18,
  vision__id__enum_values_by_name,
  1,
  vision__id__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue vision__type__enum_values_by_number[5] =
{
  { "OTHERS", "VISION__TYPE__OTHERS", 0 },
  { "HUMAN", "VISION__TYPE__HUMAN", 1 },
  { "VEHICLE", "VISION__TYPE__VEHICLE", 2 },
  { "MOTORCYCLE", "VISION__TYPE__MOTORCYCLE", 3 },
  { "ANIMAL", "VISION__TYPE__ANIMAL", 4 },
};
static const ProtobufCIntRange vision__type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex vision__type__enum_values_by_name[5] =
{
  { "ANIMAL", 4 },
  { "HUMAN", 1 },
  { "MOTORCYCLE", 3 },
  { "OTHERS", 0 },
  { "VEHICLE", 2 },
};
const ProtobufCEnumDescriptor vision__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "vision.TYPE",
  "TYPE",
  "Vision__TYPE",
  "vision",
  5,
  vision__type__enum_values_by_number,
  5,
  vision__type__enum_values_by_name,
  1,
  vision__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue vision__abnormaltype__enum_values_by_number[5] =
{
  { "DEFAULT_A", "VISION__ABNORMALTYPE__DEFAULT_A", 0 },
  { "STOP_CAR1", "VISION__ABNORMALTYPE__STOP_CAR1", 1 },
  { "STOP_CAR2", "VISION__ABNORMALTYPE__STOP_CAR2", 2 },
  { "CONTINUOUS_DIVERSION", "VISION__ABNORMALTYPE__CONTINUOUS_DIVERSION", 3 },
  { "LINE_PRESSING", "VISION__ABNORMALTYPE__LINE_PRESSING", 4 },
};
static const ProtobufCIntRange vision__abnormaltype__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex vision__abnormaltype__enum_values_by_name[5] =
{
  { "CONTINUOUS_DIVERSION", 3 },
  { "DEFAULT_A", 0 },
  { "LINE_PRESSING", 4 },
  { "STOP_CAR1", 1 },
  { "STOP_CAR2", 2 },
};
const ProtobufCEnumDescriptor vision__abnormaltype__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "vision.ABNORMALTYPE",
  "ABNORMALTYPE",
  "Vision__ABNORMALTYPE",
  "vision",
  5,
  vision__abnormaltype__enum_values_by_number,
  5,
  vision__abnormaltype__enum_values_by_name,
  1,
  vision__abnormaltype__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
