/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTEV"
 * 	found in "LTEV.asn"
 * 	`asn1c -fskeletons-copy -fnative-types -gen-PER -pdu=auto`
 */

#ifndef	_AntiLockBrakeStatusltev_H_
#define	_AntiLockBrakeStatusltev_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AntiLockBrakeStatusltev {
	AntiLockBrakeStatusltev_unavailable	= 0,
	AntiLockBrakeStatusltev_off	= 1,
	AntiLockBrakeStatusltev_on	= 2,
	AntiLockBrakeStatusltev_engaged	= 3
} e_AntiLockBrakeStatusltev;

/* AntiLockBrakeStatusltev */
typedef long	 AntiLockBrakeStatusltev_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AntiLockBrakeStatusltev_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AntiLockBrakeStatusltev;
extern const asn_INTEGER_specifics_t asn_SPC_AntiLockBrakeStatusltev_specs_1;
asn_struct_free_f AntiLockBrakeStatusltev_free;
asn_struct_print_f AntiLockBrakeStatusltev_print;
asn_constr_check_f AntiLockBrakeStatusltev_constraint;
ber_type_decoder_f AntiLockBrakeStatusltev_decode_ber;
der_type_encoder_f AntiLockBrakeStatusltev_encode_der;
xer_type_decoder_f AntiLockBrakeStatusltev_decode_xer;
xer_type_encoder_f AntiLockBrakeStatusltev_encode_xer;
oer_type_decoder_f AntiLockBrakeStatusltev_decode_oer;
oer_type_encoder_f AntiLockBrakeStatusltev_encode_oer;
per_type_decoder_f AntiLockBrakeStatusltev_decode_uper;
per_type_encoder_f AntiLockBrakeStatusltev_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AntiLockBrakeStatusltev_H_ */
#include <asn_internal.h>
