/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTEV"
 * 	found in "LTEV.asn"
 * 	`asn1c -fskeletons-copy -fnative-types -gen-PER -pdu=auto`
 */

#ifndef	_BrakeBoostAppliedltev_H_
#define	_BrakeBoostAppliedltev_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BrakeBoostAppliedltev {
	BrakeBoostAppliedltev_unavailable	= 0,
	BrakeBoostAppliedltev_off	= 1,
	BrakeBoostAppliedltev_on	= 2
} e_BrakeBoostAppliedltev;

/* BrakeBoostAppliedltev */
typedef long	 BrakeBoostAppliedltev_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_BrakeBoostAppliedltev_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_BrakeBoostAppliedltev;
extern const asn_INTEGER_specifics_t asn_SPC_BrakeBoostAppliedltev_specs_1;
asn_struct_free_f BrakeBoostAppliedltev_free;
asn_struct_print_f BrakeBoostAppliedltev_print;
asn_constr_check_f BrakeBoostAppliedltev_constraint;
ber_type_decoder_f BrakeBoostAppliedltev_decode_ber;
der_type_encoder_f BrakeBoostAppliedltev_encode_der;
xer_type_decoder_f BrakeBoostAppliedltev_decode_xer;
xer_type_encoder_f BrakeBoostAppliedltev_encode_xer;
oer_type_decoder_f BrakeBoostAppliedltev_decode_oer;
oer_type_encoder_f BrakeBoostAppliedltev_encode_oer;
per_type_decoder_f BrakeBoostAppliedltev_decode_uper;
per_type_encoder_f BrakeBoostAppliedltev_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _BrakeBoostAppliedltev_H_ */
#include <asn_internal.h>
