/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTEV"
 * 	found in "LTEV.asn"
 * 	`asn1c -fskeletons-copy -fnative-types -gen-PER -pdu=auto`
 */

#ifndef	_BSM_H_
#define	_BSM_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MsgCountltev.h"
#include <OCTET_STRING.h>
#include "DSecondltev.h"
#include "Position3Dltev.h"
#include "PositionConfidenceSetltev.h"
#include "TransmissionStateltev.h"
#include "Speedltev.h"
#include "Headingltev.h"
#include "SteeringWheelAngleltev.h"
#include "AccelerationSet4Wayltev.h"
#include "BrakeSystemStatusltev.h"
#include "VehicleSizeltev.h"
#include "VehicleClassification.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MotionConfidenceSet;
struct VehicleSafetyExtensions;

/* BSM */
typedef struct BSM {
	MsgCountltev_t	 msgCnt;
	OCTET_STRING_t	 id;
	OCTET_STRING_t	*plateNo	/* OPTIONAL */;
	DSecondltev_t	 secMark;
	Position3Dltev_t	 pos;
	PositionConfidenceSetltev_t	 accuracy;
	TransmissionStateltev_t	 transmission;
	Speedltev_t	 speed;
	Headingltev_t	 heading;
	SteeringWheelAngleltev_t	*angle	/* OPTIONAL */;
	struct MotionConfidenceSet	*motionCfd	/* OPTIONAL */;
	AccelerationSet4Wayltev_t	 accelSet;
	BrakeSystemStatusltev_t	 brakes;
	VehicleSizeltev_t	 size;
	VehicleClassification_t	 vehicleClass;
	struct VehicleSafetyExtensions	*safetyExt	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BSM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BSM;
extern asn_SEQUENCE_specifics_t asn_SPC_BSM_specs_1;
extern asn_TYPE_member_t asn_MBR_BSM_1[16];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MotionConfidenceSet.h"
#include "VehicleSafetyExtensions.h"

#endif	/* _BSM_H_ */
#include <asn_internal.h>
