/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTEV"
 * 	found in "LTEV.asn"
 * 	`asn1c -fskeletons-copy -fnative-types -gen-PER -pdu=auto`
 */

#ifndef	_DYearltev_H_
#define	_DYearltev_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DYearltev */
typedef long	 DYearltev_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_DYearltev_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_DYearltev;
asn_struct_free_f DYearltev_free;
asn_struct_print_f DYearltev_print;
asn_constr_check_f DYearltev_constraint;
ber_type_decoder_f DYearltev_decode_ber;
der_type_encoder_f DYearltev_encode_der;
xer_type_decoder_f DYearltev_decode_xer;
xer_type_encoder_f DYearltev_encode_xer;
oer_type_decoder_f DYearltev_decode_oer;
oer_type_encoder_f DYearltev_encode_oer;
per_type_decoder_f DYearltev_decode_uper;
per_type_encoder_f DYearltev_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DYearltev_H_ */
#include <asn_internal.h>
