/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTEV"
 * 	found in "LTEV.asn"
 * 	`asn1c -fskeletons-copy -fnative-types -gen-PER -pdu=auto`
 */

#ifndef	_MinuteOfTheYearltev_H_
#define	_MinuteOfTheYearltev_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MinuteOfTheYearltev */
typedef long	 MinuteOfTheYearltev_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_MinuteOfTheYearltev_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_MinuteOfTheYearltev;
asn_struct_free_f MinuteOfTheYearltev_free;
asn_struct_print_f MinuteOfTheYearltev_print;
asn_constr_check_f MinuteOfTheYearltev_constraint;
ber_type_decoder_f MinuteOfTheYearltev_decode_ber;
der_type_encoder_f MinuteOfTheYearltev_encode_der;
xer_type_decoder_f MinuteOfTheYearltev_decode_xer;
xer_type_encoder_f MinuteOfTheYearltev_encode_xer;
oer_type_decoder_f MinuteOfTheYearltev_decode_oer;
oer_type_encoder_f MinuteOfTheYearltev_encode_oer;
per_type_decoder_f MinuteOfTheYearltev_decode_uper;
per_type_encoder_f MinuteOfTheYearltev_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MinuteOfTheYearltev_H_ */
#include <asn_internal.h>
