/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTEV"
 * 	found in "LTEV.asn"
 * 	`asn1c -fskeletons-copy -fnative-types -gen-PER -pdu=auto`
 */

#ifndef	_ParticipantData_H_
#define	_ParticipantData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ParticipantType.h"
#include <NativeInteger.h>
#include "SourceType.h"
#include <OCTET_STRING.h>
#include "DSecondltev.h"
#include "PositionOffsetLLV.h"
#include "PositionConfidenceSetltev.h"
#include "TransmissionStateltev.h"
#include "Speedltev.h"
#include "Headingltev.h"
#include "SteeringWheelAngleltev.h"
#include "VehicleSizeltev.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MotionConfidenceSet;
struct AccelerationSet4Wayltev;
struct VehicleClassification;

/* ParticipantData */
typedef struct ParticipantData {
	ParticipantType_t	 ptcType;
	long	 ptcId;
	SourceType_t	 source;
	OCTET_STRING_t	*id	/* OPTIONAL */;
	OCTET_STRING_t	*plateNo	/* OPTIONAL */;
	DSecondltev_t	 secMark;
	PositionOffsetLLV_t	 pos;
	PositionConfidenceSetltev_t	 accuracy;
	TransmissionStateltev_t	*transmission	/* OPTIONAL */;
	Speedltev_t	 speed;
	Headingltev_t	 heading;
	SteeringWheelAngleltev_t	*angle	/* OPTIONAL */;
	struct MotionConfidenceSet	*motionCfd	/* OPTIONAL */;
	struct AccelerationSet4Wayltev	*accelSet	/* OPTIONAL */;
	VehicleSizeltev_t	 size;
	struct VehicleClassification	*vehicleClass	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ParticipantData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ParticipantData;
extern asn_SEQUENCE_specifics_t asn_SPC_ParticipantData_specs_1;
extern asn_TYPE_member_t asn_MBR_ParticipantData_1[16];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MotionConfidenceSet.h"
#include "AccelerationSet4Wayltev.h"
#include "VehicleClassification.h"

#endif	/* _ParticipantData_H_ */
#include <asn_internal.h>
