/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTEV"
 * 	found in "LTEV.asn"
 * 	`asn1c -fskeletons-copy -fnative-types -gen-PER -pdu=auto`
 */

#ifndef	_VehicleLengthltev_H_
#define	_VehicleLengthltev_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleLengthltev */
typedef long	 VehicleLengthltev_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_VehicleLengthltev_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_VehicleLengthltev;
asn_struct_free_f VehicleLengthltev_free;
asn_struct_print_f VehicleLengthltev_print;
asn_constr_check_f VehicleLengthltev_constraint;
ber_type_decoder_f VehicleLengthltev_decode_ber;
der_type_encoder_f VehicleLengthltev_encode_der;
xer_type_decoder_f VehicleLengthltev_decode_xer;
xer_type_encoder_f VehicleLengthltev_encode_xer;
oer_type_decoder_f VehicleLengthltev_decode_oer;
oer_type_encoder_f VehicleLengthltev_encode_oer;
per_type_decoder_f VehicleLengthltev_decode_uper;
per_type_encoder_f VehicleLengthltev_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleLengthltev_H_ */
#include <asn_internal.h>
