/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: obu_apollo.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "obu_apollo.pb-c.h"
void   obstacle__init
                     (Obstacle         *message)
{
  static const Obstacle init_value = OBSTACLE__INIT;
  *message = init_value;
}
size_t obstacle__get_packed_size
                     (const Obstacle *message)
{
  assert(message->base.descriptor == &obstacle__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t obstacle__pack
                     (const Obstacle *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &obstacle__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t obstacle__pack_to_buffer
                     (const Obstacle *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &obstacle__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Obstacle *
       obstacle__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Obstacle *)
     protobuf_c_message_unpack (&obstacle__descriptor,
                                allocator, len, data);
}
void   obstacle__free_unpacked
                     (Obstacle *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &obstacle__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   obu_msg__init
                     (ObuMsg         *message)
{
  static const ObuMsg init_value = OBU_MSG__INIT;
  *message = init_value;
}
size_t obu_msg__get_packed_size
                     (const ObuMsg *message)
{
  assert(message->base.descriptor == &obu_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t obu_msg__pack
                     (const ObuMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &obu_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t obu_msg__pack_to_buffer
                     (const ObuMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &obu_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ObuMsg *
       obu_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ObuMsg *)
     protobuf_c_message_unpack (&obu_msg__descriptor,
                                allocator, len, data);
}
void   obu_msg__free_unpacked
                     (ObuMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &obu_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor obstacle__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Obstacle, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Obstacle, type),
    &type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lng",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Obstacle, lng),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lat",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Obstacle, lat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned obstacle__field_indices_by_name[] = {
  0,   /* field[0] = id */
  3,   /* field[3] = lat */
  2,   /* field[2] = lng */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange obstacle__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor obstacle__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Obstacle",
  "Obstacle",
  "Obstacle",
  "",
  sizeof(Obstacle),
  4,
  obstacle__field_descriptors,
  obstacle__field_indices_by_name,
  1,  obstacle__number_ranges,
  (ProtobufCMessageInit) obstacle__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor obu_msg__field_descriptors[2] =
{
  {
    "count",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ObuMsg, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "obs",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ObuMsg, n_obs),
    offsetof(ObuMsg, obs),
    &obstacle__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned obu_msg__field_indices_by_name[] = {
  0,   /* field[0] = count */
  1,   /* field[1] = obs */
};
static const ProtobufCIntRange obu_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor obu_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ObuMsg",
  "ObuMsg",
  "ObuMsg",
  "",
  sizeof(ObuMsg),
  2,
  obu_msg__field_descriptors,
  obu_msg__field_indices_by_name,
  1,  obu_msg__number_ranges,
  (ProtobufCMessageInit) obu_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue type__enum_values_by_number[3] =
{
  { "HUMAN", "TYPE__HUMAN", 1 },
  { "VEHICLE", "TYPE__VEHICLE", 2 },
  { "OTHER", "TYPE__OTHER", 3 },
};
static const ProtobufCIntRange type__value_ranges[] = {
{1, 0},{0, 3}
};
static const ProtobufCEnumValueIndex type__enum_values_by_name[3] =
{
  { "HUMAN", 0 },
  { "OTHER", 2 },
  { "VEHICLE", 1 },
};
const ProtobufCEnumDescriptor type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "TYPE",
  "TYPE",
  "TYPE",
  "",
  3,
  type__enum_values_by_number,
  3,
  type__enum_values_by_name,
  1,
  type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
