/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gps.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "gps.pb-c.h"
void   apollo__drivers__point3_d__init
                     (Apollo__Drivers__Point3D         *message)
{
  static const Apollo__Drivers__Point3D init_value = APOLLO__DRIVERS__POINT3_D__INIT;
  *message = init_value;
}
size_t apollo__drivers__point3_d__get_packed_size
                     (const Apollo__Drivers__Point3D *message)
{
  assert(message->base.descriptor == &apollo__drivers__point3_d__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t apollo__drivers__point3_d__pack
                     (const Apollo__Drivers__Point3D *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &apollo__drivers__point3_d__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t apollo__drivers__point3_d__pack_to_buffer
                     (const Apollo__Drivers__Point3D *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &apollo__drivers__point3_d__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Apollo__Drivers__Point3D *
       apollo__drivers__point3_d__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Apollo__Drivers__Point3D *)
     protobuf_c_message_unpack (&apollo__drivers__point3_d__descriptor,
                                allocator, len, data);
}
void   apollo__drivers__point3_d__free_unpacked
                     (Apollo__Drivers__Point3D *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &apollo__drivers__point3_d__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   apollo__drivers__position_wgs84__init
                     (Apollo__Drivers__PositionWGS84         *message)
{
  static const Apollo__Drivers__PositionWGS84 init_value = APOLLO__DRIVERS__POSITION_WGS84__INIT;
  *message = init_value;
}
size_t apollo__drivers__position_wgs84__get_packed_size
                     (const Apollo__Drivers__PositionWGS84 *message)
{
  assert(message->base.descriptor == &apollo__drivers__position_wgs84__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t apollo__drivers__position_wgs84__pack
                     (const Apollo__Drivers__PositionWGS84 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &apollo__drivers__position_wgs84__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t apollo__drivers__position_wgs84__pack_to_buffer
                     (const Apollo__Drivers__PositionWGS84 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &apollo__drivers__position_wgs84__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Apollo__Drivers__PositionWGS84 *
       apollo__drivers__position_wgs84__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Apollo__Drivers__PositionWGS84 *)
     protobuf_c_message_unpack (&apollo__drivers__position_wgs84__descriptor,
                                allocator, len, data);
}
void   apollo__drivers__position_wgs84__free_unpacked
                     (Apollo__Drivers__PositionWGS84 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &apollo__drivers__position_wgs84__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   apollo__drivers__ci_di_gps__init
                     (Apollo__Drivers__CiDiGps         *message)
{
  static const Apollo__Drivers__CiDiGps init_value = APOLLO__DRIVERS__CI_DI_GPS__INIT;
  *message = init_value;
}
size_t apollo__drivers__ci_di_gps__get_packed_size
                     (const Apollo__Drivers__CiDiGps *message)
{
  assert(message->base.descriptor == &apollo__drivers__ci_di_gps__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t apollo__drivers__ci_di_gps__pack
                     (const Apollo__Drivers__CiDiGps *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &apollo__drivers__ci_di_gps__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t apollo__drivers__ci_di_gps__pack_to_buffer
                     (const Apollo__Drivers__CiDiGps *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &apollo__drivers__ci_di_gps__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Apollo__Drivers__CiDiGps *
       apollo__drivers__ci_di_gps__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Apollo__Drivers__CiDiGps *)
     protobuf_c_message_unpack (&apollo__drivers__ci_di_gps__descriptor,
                                allocator, len, data);
}
void   apollo__drivers__ci_di_gps__free_unpacked
                     (Apollo__Drivers__CiDiGps *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &apollo__drivers__ci_di_gps__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor apollo__drivers__point3_d__field_descriptors[3] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Apollo__Drivers__Point3D, has_x),
    offsetof(Apollo__Drivers__Point3D, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Apollo__Drivers__Point3D, has_y),
    offsetof(Apollo__Drivers__Point3D, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "z",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Apollo__Drivers__Point3D, has_z),
    offsetof(Apollo__Drivers__Point3D, z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned apollo__drivers__point3_d__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
  2,   /* field[2] = z */
};
static const ProtobufCIntRange apollo__drivers__point3_d__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor apollo__drivers__point3_d__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "apollo.drivers.Point3D",
  "Point3D",
  "Apollo__Drivers__Point3D",
  "apollo.drivers",
  sizeof(Apollo__Drivers__Point3D),
  3,
  apollo__drivers__point3_d__field_descriptors,
  apollo__drivers__point3_d__field_indices_by_name,
  1,  apollo__drivers__point3_d__number_ranges,
  (ProtobufCMessageInit) apollo__drivers__point3_d__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor apollo__drivers__position_wgs84__field_descriptors[3] =
{
  {
    "latitude",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Apollo__Drivers__PositionWGS84, has_latitude),
    offsetof(Apollo__Drivers__PositionWGS84, latitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "longitude",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Apollo__Drivers__PositionWGS84, has_longitude),
    offsetof(Apollo__Drivers__PositionWGS84, longitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "altitude",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Apollo__Drivers__PositionWGS84, has_altitude),
    offsetof(Apollo__Drivers__PositionWGS84, altitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned apollo__drivers__position_wgs84__field_indices_by_name[] = {
  2,   /* field[2] = altitude */
  0,   /* field[0] = latitude */
  1,   /* field[1] = longitude */
};
static const ProtobufCIntRange apollo__drivers__position_wgs84__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor apollo__drivers__position_wgs84__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "apollo.drivers.PositionWGS84",
  "PositionWGS84",
  "Apollo__Drivers__PositionWGS84",
  "apollo.drivers",
  sizeof(Apollo__Drivers__PositionWGS84),
  3,
  apollo__drivers__position_wgs84__field_descriptors,
  apollo__drivers__position_wgs84__field_indices_by_name,
  1,  apollo__drivers__position_wgs84__number_ranges,
  (ProtobufCMessageInit) apollo__drivers__position_wgs84__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor apollo__drivers__ci_di_gps__field_descriptors[5] =
{
  {
    "gps_time",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Apollo__Drivers__CiDiGps, has_gps_time),
    offsetof(Apollo__Drivers__CiDiGps, gps_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "heading",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Apollo__Drivers__CiDiGps, has_heading),
    offsetof(Apollo__Drivers__CiDiGps, heading),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Apollo__Drivers__CiDiGps, position),
    &apollo__drivers__position_wgs84__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "linear_velocity",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Apollo__Drivers__CiDiGps, linear_velocity),
    &apollo__drivers__point3_d__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position_std_dev",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Apollo__Drivers__CiDiGps, position_std_dev),
    &apollo__drivers__point3_d__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned apollo__drivers__ci_di_gps__field_indices_by_name[] = {
  0,   /* field[0] = gps_time */
  1,   /* field[1] = heading */
  3,   /* field[3] = linear_velocity */
  2,   /* field[2] = position */
  4,   /* field[4] = position_std_dev */
};
static const ProtobufCIntRange apollo__drivers__ci_di_gps__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor apollo__drivers__ci_di_gps__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "apollo.drivers.CiDiGps",
  "CiDiGps",
  "Apollo__Drivers__CiDiGps",
  "apollo.drivers",
  sizeof(Apollo__Drivers__CiDiGps),
  5,
  apollo__drivers__ci_di_gps__field_descriptors,
  apollo__drivers__ci_di_gps__field_indices_by_name,
  1,  apollo__drivers__ci_di_gps__number_ranges,
  (ProtobufCMessageInit) apollo__drivers__ci_di_gps__init,
  NULL,NULL,NULL    /* reserved[123] */
};
