/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTEV"
 * 	found in "LTEV.asn"
 * 	`asn1c -fskeletons-copy -fnative-types -gen-PER -pdu=auto`
 */

#ifndef	_DHourltev_H_
#define	_DHourltev_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DHourltev */
typedef long	 DHourltev_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_DHourltev_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_DHourltev;
asn_struct_free_f DHourltev_free;
asn_struct_print_f DHourltev_print;
asn_constr_check_f DHourltev_constraint;
ber_type_decoder_f DHourltev_decode_ber;
der_type_encoder_f DHourltev_encode_der;
xer_type_decoder_f DHourltev_decode_xer;
xer_type_encoder_f DHourltev_encode_xer;
oer_type_decoder_f DHourltev_decode_oer;
oer_type_encoder_f DHourltev_encode_oer;
per_type_decoder_f DHourltev_decode_uper;
per_type_encoder_f DHourltev_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DHourltev_H_ */
#include <asn_internal.h>
