/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTEV"
 * 	found in "LTEV.asn"
 * 	`asn1c -fskeletons-copy -fnative-types -gen-PER -pdu=auto`
 */

#ifndef	_DSecondltev_H_
#define	_DSecondltev_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DSecondltev */
typedef long	 DSecondltev_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_DSecondltev_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_DSecondltev;
asn_struct_free_f DSecondltev_free;
asn_struct_print_f DSecondltev_print;
asn_constr_check_f DSecondltev_constraint;
ber_type_decoder_f DSecondltev_decode_ber;
der_type_encoder_f DSecondltev_encode_der;
xer_type_decoder_f DSecondltev_decode_xer;
xer_type_encoder_f DSecondltev_encode_xer;
oer_type_decoder_f DSecondltev_decode_oer;
oer_type_encoder_f DSecondltev_encode_oer;
per_type_decoder_f DSecondltev_decode_uper;
per_type_encoder_f DSecondltev_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DSecondltev_H_ */
#include <asn_internal.h>
