/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTEV"
 * 	found in "LTEV.asn"
 * 	`asn1c -fskeletons-copy -fnative-types -gen-PER -pdu=auto`
 */

#ifndef	_ExteriorLightsltev_H_
#define	_ExteriorLightsltev_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ExteriorLightsltev {
	ExteriorLightsltev_lowBeamHeadlightsOn	= 0,
	ExteriorLightsltev_highBeamHeadlightsOn	= 1,
	ExteriorLightsltev_leftTurnSignalOn	= 2,
	ExteriorLightsltev_rightTurnSignalOn	= 3,
	ExteriorLightsltev_hazardSignalOn	= 4,
	ExteriorLightsltev_automaticLightControlOn	= 5,
	ExteriorLightsltev_daytimeRunningLightsOn	= 6,
	ExteriorLightsltev_fogLightOn	= 7,
	ExteriorLightsltev_parkingLightsOn	= 8
} e_ExteriorLightsltev;

/* ExteriorLightsltev */
typedef BIT_STRING_t	 ExteriorLightsltev_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ExteriorLightsltev_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ExteriorLightsltev;
asn_struct_free_f ExteriorLightsltev_free;
asn_struct_print_f ExteriorLightsltev_print;
asn_constr_check_f ExteriorLightsltev_constraint;
ber_type_decoder_f ExteriorLightsltev_decode_ber;
der_type_encoder_f ExteriorLightsltev_encode_der;
xer_type_decoder_f ExteriorLightsltev_decode_xer;
xer_type_encoder_f ExteriorLightsltev_encode_xer;
oer_type_decoder_f ExteriorLightsltev_decode_oer;
oer_type_encoder_f ExteriorLightsltev_encode_oer;
per_type_decoder_f ExteriorLightsltev_decode_uper;
per_type_encoder_f ExteriorLightsltev_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ExteriorLightsltev_H_ */
#include <asn_internal.h>
