/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTEV"
 * 	found in "LTEV.asn"
 * 	`asn1c -fskeletons-copy -fnative-types -gen-PER -pdu=auto`
 */

#ifndef	_IntersectionStateltev_H_
#define	_IntersectionStateltev_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NodeReferenceID.h"
#include "IntersectionStatusObjectltev.h"
#include "MinuteOfTheYearltev.h"
#include "DSecondltev.h"
#include "PhaseList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IntersectionStateltev */
typedef struct IntersectionStateltev {
	NodeReferenceID_t	 intersectionId;
	IntersectionStatusObjectltev_t	 status;
	MinuteOfTheYearltev_t	*moy	/* OPTIONAL */;
	DSecondltev_t	*timeStamp	/* OPTIONAL */;
	PhaseList_t	 phases;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IntersectionStateltev_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IntersectionStateltev;
extern asn_SEQUENCE_specifics_t asn_SPC_IntersectionStateltev_specs_1;
extern asn_TYPE_member_t asn_MBR_IntersectionStateltev_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _IntersectionStateltev_H_ */
#include <asn_internal.h>
