/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTEV"
 * 	found in "LTEV.asn"
 * 	`asn1c -fskeletons-copy -fnative-types -gen-PER -pdu=auto`
 */

#ifndef	_SteeringWheelAngleltev_H_
#define	_SteeringWheelAngleltev_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SteeringWheelAngleltev */
typedef long	 SteeringWheelAngleltev_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SteeringWheelAngleltev_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SteeringWheelAngleltev;
asn_struct_free_f SteeringWheelAngleltev_free;
asn_struct_print_f SteeringWheelAngleltev_print;
asn_constr_check_f SteeringWheelAngleltev_constraint;
ber_type_decoder_f SteeringWheelAngleltev_decode_ber;
der_type_encoder_f SteeringWheelAngleltev_encode_der;
xer_type_decoder_f SteeringWheelAngleltev_decode_xer;
xer_type_encoder_f SteeringWheelAngleltev_encode_xer;
oer_type_decoder_f SteeringWheelAngleltev_decode_oer;
oer_type_encoder_f SteeringWheelAngleltev_encode_oer;
per_type_decoder_f SteeringWheelAngleltev_decode_uper;
per_type_encoder_f SteeringWheelAngleltev_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SteeringWheelAngleltev_H_ */
#include <asn_internal.h>
