/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "LTEV"
 * 	found in "LTEV.asn"
 * 	`asn1c -fskeletons-copy -fnative-types -gen-PER -pdu=auto`
 */

#ifndef	_VehicleSizeltev_H_
#define	_VehicleSizeltev_H_


#include <asn_application.h>

/* Including external dependencies */
#include "VehicleWidthltev.h"
#include "VehicleLengthltev.h"
#include "VehicleHeightltev.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleSizeltev */
typedef struct VehicleSizeltev {
	VehicleWidthltev_t	 width;
	VehicleLengthltev_t	 vehicleLength;
	VehicleHeightltev_t	*vehicleHeight	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleSizeltev_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleSizeltev;
extern asn_SEQUENCE_specifics_t asn_SPC_VehicleSizeltev_specs_1;
extern asn_TYPE_member_t asn_MBR_VehicleSizeltev_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleSizeltev_H_ */
#include <asn_internal.h>
