/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: perception.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "perception.pb-c.h"
void   perception__position__init
                     (Perception__Position         *message)
{
  static const Perception__Position init_value = PERCEPTION__POSITION__INIT;
  *message = init_value;
}
size_t perception__position__get_packed_size
                     (const Perception__Position *message)
{
  assert(message->base.descriptor == &perception__position__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perception__position__pack
                     (const Perception__Position *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perception__position__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perception__position__pack_to_buffer
                     (const Perception__Position *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perception__position__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perception__Position *
       perception__position__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perception__Position *)
     protobuf_c_message_unpack (&perception__position__descriptor,
                                allocator, len, data);
}
void   perception__position__free_unpacked
                     (Perception__Position *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &perception__position__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perception__timestamp__init
                     (Perception__Timestamp         *message)
{
  static const Perception__Timestamp init_value = PERCEPTION__TIMESTAMP__INIT;
  *message = init_value;
}
size_t perception__timestamp__get_packed_size
                     (const Perception__Timestamp *message)
{
  assert(message->base.descriptor == &perception__timestamp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perception__timestamp__pack
                     (const Perception__Timestamp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perception__timestamp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perception__timestamp__pack_to_buffer
                     (const Perception__Timestamp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perception__timestamp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perception__Timestamp *
       perception__timestamp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perception__Timestamp *)
     protobuf_c_message_unpack (&perception__timestamp__descriptor,
                                allocator, len, data);
}
void   perception__timestamp__free_unpacked
                     (Perception__Timestamp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &perception__timestamp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perception__size__init
                     (Perception__Size         *message)
{
  static const Perception__Size init_value = PERCEPTION__SIZE__INIT;
  *message = init_value;
}
size_t perception__size__get_packed_size
                     (const Perception__Size *message)
{
  assert(message->base.descriptor == &perception__size__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perception__size__pack
                     (const Perception__Size *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perception__size__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perception__size__pack_to_buffer
                     (const Perception__Size *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perception__size__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perception__Size *
       perception__size__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perception__Size *)
     protobuf_c_message_unpack (&perception__size__descriptor,
                                allocator, len, data);
}
void   perception__size__free_unpacked
                     (Perception__Size *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &perception__size__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perception__lane_info_ex__init
                     (Perception__LaneInfoEx         *message)
{
  static const Perception__LaneInfoEx init_value = PERCEPTION__LANE_INFO_EX__INIT;
  *message = init_value;
}
size_t perception__lane_info_ex__get_packed_size
                     (const Perception__LaneInfoEx *message)
{
  assert(message->base.descriptor == &perception__lane_info_ex__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perception__lane_info_ex__pack
                     (const Perception__LaneInfoEx *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perception__lane_info_ex__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perception__lane_info_ex__pack_to_buffer
                     (const Perception__LaneInfoEx *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perception__lane_info_ex__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perception__LaneInfoEx *
       perception__lane_info_ex__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perception__LaneInfoEx *)
     protobuf_c_message_unpack (&perception__lane_info_ex__descriptor,
                                allocator, len, data);
}
void   perception__lane_info_ex__free_unpacked
                     (Perception__LaneInfoEx *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &perception__lane_info_ex__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perception__lane_area__init
                     (Perception__LaneArea         *message)
{
  static const Perception__LaneArea init_value = PERCEPTION__LANE_AREA__INIT;
  *message = init_value;
}
size_t perception__lane_area__get_packed_size
                     (const Perception__LaneArea *message)
{
  assert(message->base.descriptor == &perception__lane_area__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perception__lane_area__pack
                     (const Perception__LaneArea *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perception__lane_area__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perception__lane_area__pack_to_buffer
                     (const Perception__LaneArea *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perception__lane_area__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perception__LaneArea *
       perception__lane_area__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perception__LaneArea *)
     protobuf_c_message_unpack (&perception__lane_area__descriptor,
                                allocator, len, data);
}
void   perception__lane_area__free_unpacked
                     (Perception__LaneArea *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &perception__lane_area__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perception__jam__init
                     (Perception__Jam         *message)
{
  static const Perception__Jam init_value = PERCEPTION__JAM__INIT;
  *message = init_value;
}
size_t perception__jam__get_packed_size
                     (const Perception__Jam *message)
{
  assert(message->base.descriptor == &perception__jam__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perception__jam__pack
                     (const Perception__Jam *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perception__jam__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perception__jam__pack_to_buffer
                     (const Perception__Jam *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perception__jam__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perception__Jam *
       perception__jam__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perception__Jam *)
     protobuf_c_message_unpack (&perception__jam__descriptor,
                                allocator, len, data);
}
void   perception__jam__free_unpacked
                     (Perception__Jam *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &perception__jam__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perception__flow__init
                     (Perception__Flow         *message)
{
  static const Perception__Flow init_value = PERCEPTION__FLOW__INIT;
  *message = init_value;
}
size_t perception__flow__get_packed_size
                     (const Perception__Flow *message)
{
  assert(message->base.descriptor == &perception__flow__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perception__flow__pack
                     (const Perception__Flow *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perception__flow__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perception__flow__pack_to_buffer
                     (const Perception__Flow *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perception__flow__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perception__Flow *
       perception__flow__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perception__Flow *)
     protobuf_c_message_unpack (&perception__flow__descriptor,
                                allocator, len, data);
}
void   perception__flow__free_unpacked
                     (Perception__Flow *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &perception__flow__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perception__traffic_flow__init
                     (Perception__TrafficFlow         *message)
{
  static const Perception__TrafficFlow init_value = PERCEPTION__TRAFFIC_FLOW__INIT;
  *message = init_value;
}
size_t perception__traffic_flow__get_packed_size
                     (const Perception__TrafficFlow *message)
{
  assert(message->base.descriptor == &perception__traffic_flow__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perception__traffic_flow__pack
                     (const Perception__TrafficFlow *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perception__traffic_flow__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perception__traffic_flow__pack_to_buffer
                     (const Perception__TrafficFlow *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perception__traffic_flow__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perception__TrafficFlow *
       perception__traffic_flow__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perception__TrafficFlow *)
     protobuf_c_message_unpack (&perception__traffic_flow__descriptor,
                                allocator, len, data);
}
void   perception__traffic_flow__free_unpacked
                     (Perception__TrafficFlow *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &perception__traffic_flow__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perception__queue_length__init
                     (Perception__QueueLength         *message)
{
  static const Perception__QueueLength init_value = PERCEPTION__QUEUE_LENGTH__INIT;
  *message = init_value;
}
size_t perception__queue_length__get_packed_size
                     (const Perception__QueueLength *message)
{
  assert(message->base.descriptor == &perception__queue_length__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perception__queue_length__pack
                     (const Perception__QueueLength *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perception__queue_length__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perception__queue_length__pack_to_buffer
                     (const Perception__QueueLength *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perception__queue_length__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perception__QueueLength *
       perception__queue_length__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perception__QueueLength *)
     protobuf_c_message_unpack (&perception__queue_length__descriptor,
                                allocator, len, data);
}
void   perception__queue_length__free_unpacked
                     (Perception__QueueLength *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &perception__queue_length__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perception__target__init
                     (Perception__Target         *message)
{
  static const Perception__Target init_value = PERCEPTION__TARGET__INIT;
  *message = init_value;
}
size_t perception__target__get_packed_size
                     (const Perception__Target *message)
{
  assert(message->base.descriptor == &perception__target__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perception__target__pack
                     (const Perception__Target *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perception__target__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perception__target__pack_to_buffer
                     (const Perception__Target *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perception__target__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perception__Target *
       perception__target__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perception__Target *)
     protobuf_c_message_unpack (&perception__target__descriptor,
                                allocator, len, data);
}
void   perception__target__free_unpacked
                     (Perception__Target *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &perception__target__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perception__visibility_msg__init
                     (Perception__VisibilityMsg         *message)
{
  static const Perception__VisibilityMsg init_value = PERCEPTION__VISIBILITY_MSG__INIT;
  *message = init_value;
}
size_t perception__visibility_msg__get_packed_size
                     (const Perception__VisibilityMsg *message)
{
  assert(message->base.descriptor == &perception__visibility_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perception__visibility_msg__pack
                     (const Perception__VisibilityMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perception__visibility_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perception__visibility_msg__pack_to_buffer
                     (const Perception__VisibilityMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perception__visibility_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perception__VisibilityMsg *
       perception__visibility_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perception__VisibilityMsg *)
     protobuf_c_message_unpack (&perception__visibility_msg__descriptor,
                                allocator, len, data);
}
void   perception__visibility_msg__free_unpacked
                     (Perception__VisibilityMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &perception__visibility_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perception__lane_area_msg__init
                     (Perception__LaneAreaMsg         *message)
{
  static const Perception__LaneAreaMsg init_value = PERCEPTION__LANE_AREA_MSG__INIT;
  *message = init_value;
}
size_t perception__lane_area_msg__get_packed_size
                     (const Perception__LaneAreaMsg *message)
{
  assert(message->base.descriptor == &perception__lane_area_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perception__lane_area_msg__pack
                     (const Perception__LaneAreaMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perception__lane_area_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perception__lane_area_msg__pack_to_buffer
                     (const Perception__LaneAreaMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perception__lane_area_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perception__LaneAreaMsg *
       perception__lane_area_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perception__LaneAreaMsg *)
     protobuf_c_message_unpack (&perception__lane_area_msg__descriptor,
                                allocator, len, data);
}
void   perception__lane_area_msg__free_unpacked
                     (Perception__LaneAreaMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &perception__lane_area_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perception__jam_msg__init
                     (Perception__JamMsg         *message)
{
  static const Perception__JamMsg init_value = PERCEPTION__JAM_MSG__INIT;
  *message = init_value;
}
size_t perception__jam_msg__get_packed_size
                     (const Perception__JamMsg *message)
{
  assert(message->base.descriptor == &perception__jam_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perception__jam_msg__pack
                     (const Perception__JamMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perception__jam_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perception__jam_msg__pack_to_buffer
                     (const Perception__JamMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perception__jam_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perception__JamMsg *
       perception__jam_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perception__JamMsg *)
     protobuf_c_message_unpack (&perception__jam_msg__descriptor,
                                allocator, len, data);
}
void   perception__jam_msg__free_unpacked
                     (Perception__JamMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &perception__jam_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perception__dynamic_timing_msg__init
                     (Perception__DynamicTimingMsg         *message)
{
  static const Perception__DynamicTimingMsg init_value = PERCEPTION__DYNAMIC_TIMING_MSG__INIT;
  *message = init_value;
}
size_t perception__dynamic_timing_msg__get_packed_size
                     (const Perception__DynamicTimingMsg *message)
{
  assert(message->base.descriptor == &perception__dynamic_timing_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perception__dynamic_timing_msg__pack
                     (const Perception__DynamicTimingMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perception__dynamic_timing_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perception__dynamic_timing_msg__pack_to_buffer
                     (const Perception__DynamicTimingMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perception__dynamic_timing_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perception__DynamicTimingMsg *
       perception__dynamic_timing_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perception__DynamicTimingMsg *)
     protobuf_c_message_unpack (&perception__dynamic_timing_msg__descriptor,
                                allocator, len, data);
}
void   perception__dynamic_timing_msg__free_unpacked
                     (Perception__DynamicTimingMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &perception__dynamic_timing_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perception__target_msg__init
                     (Perception__TargetMsg         *message)
{
  static const Perception__TargetMsg init_value = PERCEPTION__TARGET_MSG__INIT;
  *message = init_value;
}
size_t perception__target_msg__get_packed_size
                     (const Perception__TargetMsg *message)
{
  assert(message->base.descriptor == &perception__target_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perception__target_msg__pack
                     (const Perception__TargetMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perception__target_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perception__target_msg__pack_to_buffer
                     (const Perception__TargetMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perception__target_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perception__TargetMsg *
       perception__target_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perception__TargetMsg *)
     protobuf_c_message_unpack (&perception__target_msg__descriptor,
                                allocator, len, data);
}
void   perception__target_msg__free_unpacked
                     (Perception__TargetMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &perception__target_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perception__warn_msg__init
                     (Perception__WarnMsg         *message)
{
  static const Perception__WarnMsg init_value = PERCEPTION__WARN_MSG__INIT;
  *message = init_value;
}
size_t perception__warn_msg__get_packed_size
                     (const Perception__WarnMsg *message)
{
  assert(message->base.descriptor == &perception__warn_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perception__warn_msg__pack
                     (const Perception__WarnMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perception__warn_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perception__warn_msg__pack_to_buffer
                     (const Perception__WarnMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perception__warn_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perception__WarnMsg *
       perception__warn_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perception__WarnMsg *)
     protobuf_c_message_unpack (&perception__warn_msg__descriptor,
                                allocator, len, data);
}
void   perception__warn_msg__free_unpacked
                     (Perception__WarnMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &perception__warn_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perception__traffic_flow_msg__init
                     (Perception__TrafficFlowMsg         *message)
{
  static const Perception__TrafficFlowMsg init_value = PERCEPTION__TRAFFIC_FLOW_MSG__INIT;
  *message = init_value;
}
size_t perception__traffic_flow_msg__get_packed_size
                     (const Perception__TrafficFlowMsg *message)
{
  assert(message->base.descriptor == &perception__traffic_flow_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perception__traffic_flow_msg__pack
                     (const Perception__TrafficFlowMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perception__traffic_flow_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perception__traffic_flow_msg__pack_to_buffer
                     (const Perception__TrafficFlowMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perception__traffic_flow_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perception__TrafficFlowMsg *
       perception__traffic_flow_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perception__TrafficFlowMsg *)
     protobuf_c_message_unpack (&perception__traffic_flow_msg__descriptor,
                                allocator, len, data);
}
void   perception__traffic_flow_msg__free_unpacked
                     (Perception__TrafficFlowMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &perception__traffic_flow_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perception__queue_msg__init
                     (Perception__QueueMsg         *message)
{
  static const Perception__QueueMsg init_value = PERCEPTION__QUEUE_MSG__INIT;
  *message = init_value;
}
size_t perception__queue_msg__get_packed_size
                     (const Perception__QueueMsg *message)
{
  assert(message->base.descriptor == &perception__queue_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perception__queue_msg__pack
                     (const Perception__QueueMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perception__queue_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perception__queue_msg__pack_to_buffer
                     (const Perception__QueueMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perception__queue_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perception__QueueMsg *
       perception__queue_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perception__QueueMsg *)
     protobuf_c_message_unpack (&perception__queue_msg__descriptor,
                                allocator, len, data);
}
void   perception__queue_msg__free_unpacked
                     (Perception__QueueMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &perception__queue_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   perception__perception_msg__init
                     (Perception__PerceptionMsg         *message)
{
  static const Perception__PerceptionMsg init_value = PERCEPTION__PERCEPTION_MSG__INIT;
  *message = init_value;
}
size_t perception__perception_msg__get_packed_size
                     (const Perception__PerceptionMsg *message)
{
  assert(message->base.descriptor == &perception__perception_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t perception__perception_msg__pack
                     (const Perception__PerceptionMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &perception__perception_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t perception__perception_msg__pack_to_buffer
                     (const Perception__PerceptionMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &perception__perception_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Perception__PerceptionMsg *
       perception__perception_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Perception__PerceptionMsg *)
     protobuf_c_message_unpack (&perception__perception_msg__descriptor,
                                allocator, len, data);
}
void   perception__perception_msg__free_unpacked
                     (Perception__PerceptionMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &perception__perception_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor perception__position__field_descriptors[3] =
{
  {
    "lon",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Perception__Position, lon),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lat",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Perception__Position, lat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "elevation",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Perception__Position, has_elevation),
    offsetof(Perception__Position, elevation),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perception__position__field_indices_by_name[] = {
  2,   /* field[2] = elevation */
  1,   /* field[1] = lat */
  0,   /* field[0] = lon */
};
static const ProtobufCIntRange perception__position__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor perception__position__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perception.Position",
  "Position",
  "Perception__Position",
  "perception",
  sizeof(Perception__Position),
  3,
  perception__position__field_descriptors,
  perception__position__field_indices_by_name,
  1,  perception__position__number_ranges,
  (ProtobufCMessageInit) perception__position__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perception__timestamp__field_descriptors[2] =
{
  {
    "seconds",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Perception__Timestamp, seconds),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nanos",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Perception__Timestamp, nanos),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perception__timestamp__field_indices_by_name[] = {
  1,   /* field[1] = nanos */
  0,   /* field[0] = seconds */
};
static const ProtobufCIntRange perception__timestamp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor perception__timestamp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perception.Timestamp",
  "Timestamp",
  "Perception__Timestamp",
  "perception",
  sizeof(Perception__Timestamp),
  2,
  perception__timestamp__field_descriptors,
  perception__timestamp__field_indices_by_name,
  1,  perception__timestamp__number_ranges,
  (ProtobufCMessageInit) perception__timestamp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perception__size__field_descriptors[3] =
{
  {
    "length",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Perception__Size, length),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "width",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Perception__Size, width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Perception__Size, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perception__size__field_indices_by_name[] = {
  2,   /* field[2] = height */
  0,   /* field[0] = length */
  1,   /* field[1] = width */
};
static const ProtobufCIntRange perception__size__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor perception__size__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perception.Size",
  "Size",
  "Perception__Size",
  "perception",
  sizeof(Perception__Size),
  3,
  perception__size__field_descriptors,
  perception__size__field_indices_by_name,
  1,  perception__size__number_ranges,
  (ProtobufCMessageInit) perception__size__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perception__lane_info_ex__field_descriptors[4] =
{
  {
    "lane_info",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Perception__LaneInfoEx, lane_info),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lane_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Perception__LaneInfoEx, lane_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lane_count",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Perception__LaneInfoEx, lane_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lane_heading",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Perception__LaneInfoEx, lane_heading),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perception__lane_info_ex__field_indices_by_name[] = {
  2,   /* field[2] = lane_count */
  3,   /* field[3] = lane_heading */
  1,   /* field[1] = lane_id */
  0,   /* field[0] = lane_info */
};
static const ProtobufCIntRange perception__lane_info_ex__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor perception__lane_info_ex__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perception.LaneInfoEx",
  "LaneInfoEx",
  "Perception__LaneInfoEx",
  "perception",
  sizeof(Perception__LaneInfoEx),
  4,
  perception__lane_info_ex__field_descriptors,
  perception__lane_info_ex__field_indices_by_name,
  1,  perception__lane_info_ex__number_ranges,
  (ProtobufCMessageInit) perception__lane_info_ex__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perception__lane_area__field_descriptors[5] =
{
  {
    "pos",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perception__LaneArea, n_pos),
    offsetof(Perception__LaneArea, pos),
    &perception__position__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "camera",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Perception__LaneArea, has_camera),
    offsetof(Perception__LaneArea, camera),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lane_id",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Perception__LaneArea, has_lane_id),
    offsetof(Perception__LaneArea, lane_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lane_heading",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Perception__LaneArea, has_lane_heading),
    offsetof(Perception__LaneArea, lane_heading),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ware",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Perception__LaneArea, has_ware),
    offsetof(Perception__LaneArea, ware),
    &perception__ware_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perception__lane_area__field_indices_by_name[] = {
  1,   /* field[1] = camera */
  3,   /* field[3] = lane_heading */
  2,   /* field[2] = lane_id */
  0,   /* field[0] = pos */
  4,   /* field[4] = ware */
};
static const ProtobufCIntRange perception__lane_area__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor perception__lane_area__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perception.LaneArea",
  "LaneArea",
  "Perception__LaneArea",
  "perception",
  sizeof(Perception__LaneArea),
  5,
  perception__lane_area__field_descriptors,
  perception__lane_area__field_indices_by_name,
  1,  perception__lane_area__number_ranges,
  (ProtobufCMessageInit) perception__lane_area__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perception__jam__field_descriptors[5] =
{
  {
    "vehicle_num",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Perception__Jam, vehicle_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vehicle_velocity",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Perception__Jam, vehicle_velocity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lane_heading",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Perception__Jam, lane_heading),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vehicle_flow",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Perception__Jam, n_vehicle_flow),
    offsetof(Perception__Jam, vehicle_flow),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lane_id",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Perception__Jam, has_lane_id),
    offsetof(Perception__Jam, lane_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perception__jam__field_indices_by_name[] = {
  2,   /* field[2] = lane_heading */
  4,   /* field[4] = lane_id */
  3,   /* field[3] = vehicle_flow */
  0,   /* field[0] = vehicle_num */
  1,   /* field[1] = vehicle_velocity */
};
static const ProtobufCIntRange perception__jam__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor perception__jam__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perception.Jam",
  "Jam",
  "Perception__Jam",
  "perception",
  sizeof(Perception__Jam),
  5,
  perception__jam__field_descriptors,
  perception__jam__field_indices_by_name,
  1,  perception__jam__number_ranges,
  (ProtobufCMessageInit) perception__jam__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue perception__flow__traffic_sig__enum_values_by_number[3] =
{
  { "UNKNOWN", "PERCEPTION__FLOW__TRAFFIC_SIG__UNKNOWN", 0 },
  { "Y2G", "PERCEPTION__FLOW__TRAFFIC_SIG__Y2G", 1 },
  { "OVER", "PERCEPTION__FLOW__TRAFFIC_SIG__OVER", 2 },
};
static const ProtobufCIntRange perception__flow__traffic_sig__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex perception__flow__traffic_sig__enum_values_by_name[3] =
{
  { "OVER", 2 },
  { "UNKNOWN", 0 },
  { "Y2G", 1 },
};
const ProtobufCEnumDescriptor perception__flow__traffic_sig__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "perception.Flow.TrafficSig",
  "TrafficSig",
  "Perception__Flow__TrafficSig",
  "perception",
  3,
  perception__flow__traffic_sig__enum_values_by_number,
  3,
  perception__flow__traffic_sig__enum_values_by_name,
  1,
  perception__flow__traffic_sig__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor perception__flow__field_descriptors[4] =
{
  {
    "camera",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Perception__Flow, has_camera),
    offsetof(Perception__Flow, camera),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vehicle_num",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Perception__Flow, n_vehicle_num),
    offsetof(Perception__Flow, vehicle_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pass_num",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Perception__Flow, n_pass_num),
    offsetof(Perception__Flow, pass_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signal",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Perception__Flow, has_signal),
    offsetof(Perception__Flow, signal),
    &perception__flow__traffic_sig__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perception__flow__field_indices_by_name[] = {
  0,   /* field[0] = camera */
  2,   /* field[2] = pass_num */
  3,   /* field[3] = signal */
  1,   /* field[1] = vehicle_num */
};
static const ProtobufCIntRange perception__flow__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor perception__flow__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perception.Flow",
  "Flow",
  "Perception__Flow",
  "perception",
  sizeof(Perception__Flow),
  4,
  perception__flow__field_descriptors,
  perception__flow__field_indices_by_name,
  1,  perception__flow__number_ranges,
  (ProtobufCMessageInit) perception__flow__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perception__traffic_flow__field_descriptors[5] =
{
  {
    "node_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Perception__TrafficFlow, node_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "link_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Perception__TrafficFlow, link_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vehicle_num",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Perception__TrafficFlow, n_vehicle_num),
    offsetof(Perception__TrafficFlow, vehicle_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maneuvers",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Perception__TrafficFlow, n_maneuvers),
    offsetof(Perception__TrafficFlow, maneuvers),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pass_num",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Perception__TrafficFlow, n_pass_num),
    offsetof(Perception__TrafficFlow, pass_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perception__traffic_flow__field_indices_by_name[] = {
  1,   /* field[1] = link_id */
  3,   /* field[3] = maneuvers */
  0,   /* field[0] = node_id */
  4,   /* field[4] = pass_num */
  2,   /* field[2] = vehicle_num */
};
static const ProtobufCIntRange perception__traffic_flow__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor perception__traffic_flow__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perception.TrafficFlow",
  "TrafficFlow",
  "Perception__TrafficFlow",
  "perception",
  sizeof(Perception__TrafficFlow),
  5,
  perception__traffic_flow__field_descriptors,
  perception__traffic_flow__field_indices_by_name,
  1,  perception__traffic_flow__number_ranges,
  (ProtobufCMessageInit) perception__traffic_flow__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perception__queue_length__field_descriptors[4] =
{
  {
    "node_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Perception__QueueLength, node_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "link_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Perception__QueueLength, link_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vehicle_num",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Perception__QueueLength, n_vehicle_num),
    offsetof(Perception__QueueLength, vehicle_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maneuvers",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Perception__QueueLength, n_maneuvers),
    offsetof(Perception__QueueLength, maneuvers),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perception__queue_length__field_indices_by_name[] = {
  1,   /* field[1] = link_id */
  3,   /* field[3] = maneuvers */
  0,   /* field[0] = node_id */
  2,   /* field[2] = vehicle_num */
};
static const ProtobufCIntRange perception__queue_length__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor perception__queue_length__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perception.QueueLength",
  "QueueLength",
  "Perception__QueueLength",
  "perception",
  sizeof(Perception__QueueLength),
  4,
  perception__queue_length__field_descriptors,
  perception__queue_length__field_indices_by_name,
  1,  perception__queue_length__number_ranges,
  (ProtobufCMessageInit) perception__queue_length__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perception__target__field_descriptors[21] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Perception__Target, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Perception__Target, type),
    &perception__target_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Perception__Target, pos),
    &perception__position__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "camera",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Perception__Target, has_camera),
    offsetof(Perception__Target, camera),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "velocity",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Perception__Target, has_velocity),
    offsetof(Perception__Target, velocity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "heading",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Perception__Target, has_heading),
    offsetof(Perception__Target, heading),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "distance",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Perception__Target, has_distance),
    offsetof(Perception__Target, distance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Perception__Target, size),
    &perception__size__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "approach_judge",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Perception__Target, has_approach_judge),
    offsetof(Perception__Target, approach_judge),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Perception__Target, has_source),
    offsetof(Perception__Target, source),
    &perception__source__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "capture_id",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Perception__Target, has_capture_id),
    offsetof(Perception__Target, capture_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "in_lane",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Perception__Target, has_in_lane),
    offsetof(Perception__Target, in_lane),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lane_id",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Perception__Target, has_lane_id),
    offsetof(Perception__Target, lane_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lane_heading",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Perception__Target, has_lane_heading),
    offsetof(Perception__Target, lane_heading),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lane_type",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Perception__Target, has_lane_type),
    offsetof(Perception__Target, lane_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lane_ex",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Perception__Target, lane_ex),
    &perception__lane_info_ex__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "license_plate",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Perception__Target, license_plate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "car_type",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Perception__Target, has_car_type),
    offsetof(Perception__Target, car_type),
    &perception__car_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "car_status",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Perception__Target, has_car_status),
    offsetof(Perception__Target, car_status),
    &perception__car_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "confidence",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Perception__Target, has_confidence),
    offsetof(Perception__Target, confidence),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rcs",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Perception__Target, has_rcs),
    offsetof(Perception__Target, rcs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perception__target__field_indices_by_name[] = {
  8,   /* field[8] = approach_judge */
  3,   /* field[3] = camera */
  10,   /* field[10] = capture_id */
  18,   /* field[18] = car_status */
  17,   /* field[17] = car_type */
  19,   /* field[19] = confidence */
  6,   /* field[6] = distance */
  5,   /* field[5] = heading */
  0,   /* field[0] = id */
  11,   /* field[11] = in_lane */
  15,   /* field[15] = lane_ex */
  13,   /* field[13] = lane_heading */
  12,   /* field[12] = lane_id */
  14,   /* field[14] = lane_type */
  16,   /* field[16] = license_plate */
  2,   /* field[2] = pos */
  20,   /* field[20] = rcs */
  7,   /* field[7] = size */
  9,   /* field[9] = source */
  1,   /* field[1] = type */
  4,   /* field[4] = velocity */
};
static const ProtobufCIntRange perception__target__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 21 }
};
const ProtobufCMessageDescriptor perception__target__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perception.Target",
  "Target",
  "Perception__Target",
  "perception",
  sizeof(Perception__Target),
  21,
  perception__target__field_descriptors,
  perception__target__field_indices_by_name,
  1,  perception__target__number_ranges,
  (ProtobufCMessageInit) perception__target__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perception__visibility_msg__field_descriptors[2] =
{
  {
    "level",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Perception__VisibilityMsg, level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "camera_pos",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Perception__VisibilityMsg, camera_pos),
    &perception__position__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perception__visibility_msg__field_indices_by_name[] = {
  1,   /* field[1] = camera_pos */
  0,   /* field[0] = level */
};
static const ProtobufCIntRange perception__visibility_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor perception__visibility_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perception.VisibilityMsg",
  "VisibilityMsg",
  "Perception__VisibilityMsg",
  "perception",
  sizeof(Perception__VisibilityMsg),
  2,
  perception__visibility_msg__field_descriptors,
  perception__visibility_msg__field_indices_by_name,
  1,  perception__visibility_msg__number_ranges,
  (ProtobufCMessageInit) perception__visibility_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perception__lane_area_msg__field_descriptors[1] =
{
  {
    "area",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perception__LaneAreaMsg, n_area),
    offsetof(Perception__LaneAreaMsg, area),
    &perception__lane_area__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perception__lane_area_msg__field_indices_by_name[] = {
  0,   /* field[0] = area */
};
static const ProtobufCIntRange perception__lane_area_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor perception__lane_area_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perception.LaneAreaMsg",
  "LaneAreaMsg",
  "Perception__LaneAreaMsg",
  "perception",
  sizeof(Perception__LaneAreaMsg),
  1,
  perception__lane_area_msg__field_descriptors,
  perception__lane_area_msg__field_indices_by_name,
  1,  perception__lane_area_msg__number_ranges,
  (ProtobufCMessageInit) perception__lane_area_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perception__jam_msg__field_descriptors[1] =
{
  {
    "jam",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perception__JamMsg, n_jam),
    offsetof(Perception__JamMsg, jam),
    &perception__jam__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perception__jam_msg__field_indices_by_name[] = {
  0,   /* field[0] = jam */
};
static const ProtobufCIntRange perception__jam_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor perception__jam_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perception.JamMsg",
  "JamMsg",
  "Perception__JamMsg",
  "perception",
  sizeof(Perception__JamMsg),
  1,
  perception__jam_msg__field_descriptors,
  perception__jam_msg__field_indices_by_name,
  1,  perception__jam_msg__number_ranges,
  (ProtobufCMessageInit) perception__jam_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perception__dynamic_timing_msg__field_descriptors[3] =
{
  {
    "flow",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perception__DynamicTimingMsg, n_flow),
    offsetof(Perception__DynamicTimingMsg, flow),
    &perception__flow__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_begin",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Perception__DynamicTimingMsg, time_begin),
    &perception__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_end",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Perception__DynamicTimingMsg, time_end),
    &perception__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perception__dynamic_timing_msg__field_indices_by_name[] = {
  0,   /* field[0] = flow */
  1,   /* field[1] = time_begin */
  2,   /* field[2] = time_end */
};
static const ProtobufCIntRange perception__dynamic_timing_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor perception__dynamic_timing_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perception.DynamicTimingMsg",
  "DynamicTimingMsg",
  "Perception__DynamicTimingMsg",
  "perception",
  sizeof(Perception__DynamicTimingMsg),
  3,
  perception__dynamic_timing_msg__field_descriptors,
  perception__dynamic_timing_msg__field_indices_by_name,
  1,  perception__dynamic_timing_msg__number_ranges,
  (ProtobufCMessageInit) perception__dynamic_timing_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perception__target_msg__field_descriptors[1] =
{
  {
    "target",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perception__TargetMsg, n_target),
    offsetof(Perception__TargetMsg, target),
    &perception__target__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perception__target_msg__field_indices_by_name[] = {
  0,   /* field[0] = target */
};
static const ProtobufCIntRange perception__target_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor perception__target_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perception.TargetMsg",
  "TargetMsg",
  "Perception__TargetMsg",
  "perception",
  sizeof(Perception__TargetMsg),
  1,
  perception__target_msg__field_descriptors,
  perception__target_msg__field_indices_by_name,
  1,  perception__target_msg__number_ranges,
  (ProtobufCMessageInit) perception__target_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perception__warn_msg__field_descriptors[1] =
{
  {
    "warn",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Perception__WarnMsg, warn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perception__warn_msg__field_indices_by_name[] = {
  0,   /* field[0] = warn */
};
static const ProtobufCIntRange perception__warn_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor perception__warn_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perception.WarnMsg",
  "WarnMsg",
  "Perception__WarnMsg",
  "perception",
  sizeof(Perception__WarnMsg),
  1,
  perception__warn_msg__field_descriptors,
  perception__warn_msg__field_indices_by_name,
  1,  perception__warn_msg__number_ranges,
  (ProtobufCMessageInit) perception__warn_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perception__traffic_flow_msg__field_descriptors[3] =
{
  {
    "flow",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perception__TrafficFlowMsg, n_flow),
    offsetof(Perception__TrafficFlowMsg, flow),
    &perception__traffic_flow__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_begin",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Perception__TrafficFlowMsg, time_begin),
    &perception__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time_end",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Perception__TrafficFlowMsg, time_end),
    &perception__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perception__traffic_flow_msg__field_indices_by_name[] = {
  0,   /* field[0] = flow */
  1,   /* field[1] = time_begin */
  2,   /* field[2] = time_end */
};
static const ProtobufCIntRange perception__traffic_flow_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor perception__traffic_flow_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perception.TrafficFlowMsg",
  "TrafficFlowMsg",
  "Perception__TrafficFlowMsg",
  "perception",
  sizeof(Perception__TrafficFlowMsg),
  3,
  perception__traffic_flow_msg__field_descriptors,
  perception__traffic_flow_msg__field_indices_by_name,
  1,  perception__traffic_flow_msg__number_ranges,
  (ProtobufCMessageInit) perception__traffic_flow_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perception__queue_msg__field_descriptors[1] =
{
  {
    "queue",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perception__QueueMsg, n_queue),
    offsetof(Perception__QueueMsg, queue),
    &perception__queue_length__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perception__queue_msg__field_indices_by_name[] = {
  0,   /* field[0] = queue */
};
static const ProtobufCIntRange perception__queue_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor perception__queue_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perception.QueueMsg",
  "QueueMsg",
  "Perception__QueueMsg",
  "perception",
  sizeof(Perception__QueueMsg),
  1,
  perception__queue_msg__field_descriptors,
  perception__queue_msg__field_indices_by_name,
  1,  perception__queue_msg__number_ranges,
  (ProtobufCMessageInit) perception__queue_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor perception__perception_msg__field_descriptors[10] =
{
  {
    "event",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Perception__PerceptionMsg, event),
    &perception__event_id__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "warn_msg",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perception__PerceptionMsg, msg_type_case),
    offsetof(Perception__PerceptionMsg, warn_msg),
    &perception__warn_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "visibility_msg",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perception__PerceptionMsg, msg_type_case),
    offsetof(Perception__PerceptionMsg, visibility_msg),
    &perception__visibility_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lane_area_msg",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perception__PerceptionMsg, msg_type_case),
    offsetof(Perception__PerceptionMsg, lane_area_msg),
    &perception__lane_area_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "jam_msg",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perception__PerceptionMsg, msg_type_case),
    offsetof(Perception__PerceptionMsg, jam_msg),
    &perception__jam_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dynamic_msg",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perception__PerceptionMsg, msg_type_case),
    offsetof(Perception__PerceptionMsg, dynamic_msg),
    &perception__dynamic_timing_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "target_msg",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perception__PerceptionMsg, msg_type_case),
    offsetof(Perception__PerceptionMsg, target_msg),
    &perception__target_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "traffic_flow_msg",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perception__PerceptionMsg, msg_type_case),
    offsetof(Perception__PerceptionMsg, traffic_flow_msg),
    &perception__traffic_flow_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "queue_msg",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Perception__PerceptionMsg, msg_type_case),
    offsetof(Perception__PerceptionMsg, queue_msg),
    &perception__queue_msg__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Perception__PerceptionMsg, time),
    &perception__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned perception__perception_msg__field_indices_by_name[] = {
  5,   /* field[5] = dynamic_msg */
  0,   /* field[0] = event */
  4,   /* field[4] = jam_msg */
  3,   /* field[3] = lane_area_msg */
  8,   /* field[8] = queue_msg */
  6,   /* field[6] = target_msg */
  9,   /* field[9] = time */
  7,   /* field[7] = traffic_flow_msg */
  2,   /* field[2] = visibility_msg */
  1,   /* field[1] = warn_msg */
};
static const ProtobufCIntRange perception__perception_msg__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 20, 9 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor perception__perception_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "perception.PerceptionMsg",
  "PerceptionMsg",
  "Perception__PerceptionMsg",
  "perception",
  sizeof(Perception__PerceptionMsg),
  10,
  perception__perception_msg__field_descriptors,
  perception__perception_msg__field_indices_by_name,
  2,  perception__perception_msg__number_ranges,
  (ProtobufCMessageInit) perception__perception_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue perception__version__enum_values_by_number[1] =
{
  { "VERSION", "PERCEPTION__VERSION__VERSION", 20201109 },
};
static const ProtobufCIntRange perception__version__value_ranges[] = {
{20201109, 0},{0, 1}
};
static const ProtobufCEnumValueIndex perception__version__enum_values_by_name[1] =
{
  { "VERSION", 0 },
};
const ProtobufCEnumDescriptor perception__version__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "perception.Version",
  "Version",
  "Perception__Version",
  "perception",
  1,
  perception__version__enum_values_by_number,
  1,
  perception__version__enum_values_by_name,
  1,
  perception__version__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue perception__event_id__enum_values_by_number[23] =
{
  { "EVENT_NONE", "PERCEPTION__EVENT_ID__EVENT_NONE", 0 },
  { "PEDESTRIAN", "PERCEPTION__EVENT_ID__PEDESTRIAN", 1 },
  { "ILLEGAL_V1", "PERCEPTION__EVENT_ID__ILLEGAL_V1", 2 },
  { "VISIBILITY", "PERCEPTION__EVENT_ID__VISIBILITY", 3 },
  { "AVAILABLE_AREA", "PERCEPTION__EVENT_ID__AVAILABLE_AREA", 4 },
  { "ABNORMAL_CAR", "PERCEPTION__EVENT_ID__ABNORMAL_CAR", 5 },
  { "ILLEGAL_V2", "PERCEPTION__EVENT_ID__ILLEGAL_V2", 6 },
  { "TRAFFIC_STATUS", "PERCEPTION__EVENT_ID__TRAFFIC_STATUS", 7 },
  { "BACKWARD_DRIVING", "PERCEPTION__EVENT_ID__BACKWARD_DRIVING", 8 },
  { "ROAD_DANGER", "PERCEPTION__EVENT_ID__ROAD_DANGER", 9 },
  { "FIRE_SMOKE", "PERCEPTION__EVENT_ID__FIRE_SMOKE", 10 },
  { "TARGET_TO_FUSION", "PERCEPTION__EVENT_ID__TARGET_TO_FUSION", 11 },
  { "TRAFFIC_JAM", "PERCEPTION__EVENT_ID__TRAFFIC_JAM", 12 },
  { "TRAFFIC_FLOW", "PERCEPTION__EVENT_ID__TRAFFIC_FLOW", 13 },
  { "SPECIALCAR", "PERCEPTION__EVENT_ID__SPECIALCAR", 14 },
  { "ACCIDENT", "PERCEPTION__EVENT_ID__ACCIDENT", 15 },
  { "ICEWARN", "PERCEPTION__EVENT_ID__ICEWARN", 16 },
  { "LANE_WARE", "PERCEPTION__EVENT_ID__LANE_WARE", 17 },
  { "SPEEDING", "PERCEPTION__EVENT_ID__SPEEDING", 18 },
  { "SNAP", "PERCEPTION__EVENT_ID__SNAP", 19 },
  { "FUSION_TO_RSU", "PERCEPTION__EVENT_ID__FUSION_TO_RSU", 20 },
  { "DYNAMIC_TIMING", "PERCEPTION__EVENT_ID__DYNAMIC_TIMING", 21 },
  { "QUEUE_LENGTH", "PERCEPTION__EVENT_ID__QUEUE_LENGTH", 22 },
};
static const ProtobufCIntRange perception__event_id__value_ranges[] = {
{0, 0},{0, 23}
};
static const ProtobufCEnumValueIndex perception__event_id__enum_values_by_name[23] =
{
  { "ABNORMAL_CAR", 5 },
  { "ACCIDENT", 15 },
  { "AVAILABLE_AREA", 4 },
  { "BACKWARD_DRIVING", 8 },
  { "DYNAMIC_TIMING", 21 },
  { "EVENT_NONE", 0 },
  { "FIRE_SMOKE", 10 },
  { "FUSION_TO_RSU", 20 },
  { "ICEWARN", 16 },
  { "ILLEGAL_V1", 2 },
  { "ILLEGAL_V2", 6 },
  { "LANE_WARE", 17 },
  { "PEDESTRIAN", 1 },
  { "QUEUE_LENGTH", 22 },
  { "ROAD_DANGER", 9 },
  { "SNAP", 19 },
  { "SPECIALCAR", 14 },
  { "SPEEDING", 18 },
  { "TARGET_TO_FUSION", 11 },
  { "TRAFFIC_FLOW", 13 },
  { "TRAFFIC_JAM", 12 },
  { "TRAFFIC_STATUS", 7 },
  { "VISIBILITY", 3 },
};
const ProtobufCEnumDescriptor perception__event_id__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "perception.EventId",
  "EventId",
  "Perception__EventId",
  "perception",
  23,
  perception__event_id__enum_values_by_number,
  23,
  perception__event_id__enum_values_by_name,
  1,
  perception__event_id__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue perception__source__enum_values_by_number[5] =
{
  { "OTHER_SOURCE", "PERCEPTION__SOURCE__OTHER_SOURCE", 0 },
  { "RADAR", "PERCEPTION__SOURCE__RADAR", 1 },
  { "VISION", "PERCEPTION__SOURCE__VISION", 2 },
  { "LIDAR", "PERCEPTION__SOURCE__LIDAR", 3 },
  { "V2X", "PERCEPTION__SOURCE__V2X", 4 },
};
static const ProtobufCIntRange perception__source__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex perception__source__enum_values_by_name[5] =
{
  { "LIDAR", 3 },
  { "OTHER_SOURCE", 0 },
  { "RADAR", 1 },
  { "V2X", 4 },
  { "VISION", 2 },
};
const ProtobufCEnumDescriptor perception__source__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "perception.Source",
  "Source",
  "Perception__Source",
  "perception",
  5,
  perception__source__enum_values_by_number,
  5,
  perception__source__enum_values_by_name,
  1,
  perception__source__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue perception__target_type__enum_values_by_number[6] =
{
  { "OTHERS", "PERCEPTION__TARGET_TYPE__OTHERS", 0 },
  { "HUMAN", "PERCEPTION__TARGET_TYPE__HUMAN", 1 },
  { "VEHICLE", "PERCEPTION__TARGET_TYPE__VEHICLE", 2 },
  { "MOTORCYCLE", "PERCEPTION__TARGET_TYPE__MOTORCYCLE", 3 },
  { "ANIMAL", "PERCEPTION__TARGET_TYPE__ANIMAL", 4 },
  { "OBSTACLE", "PERCEPTION__TARGET_TYPE__OBSTACLE", 5 },
};
static const ProtobufCIntRange perception__target_type__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex perception__target_type__enum_values_by_name[6] =
{
  { "ANIMAL", 4 },
  { "HUMAN", 1 },
  { "MOTORCYCLE", 3 },
  { "OBSTACLE", 5 },
  { "OTHERS", 0 },
  { "VEHICLE", 2 },
};
const ProtobufCEnumDescriptor perception__target_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "perception.TargetType",
  "TargetType",
  "Perception__TargetType",
  "perception",
  6,
  perception__target_type__enum_values_by_number,
  6,
  perception__target_type__enum_values_by_name,
  1,
  perception__target_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue perception__car_type__enum_values_by_number[5] =
{
  { "NORMAL", "PERCEPTION__CAR_TYPE__NORMAL", 0 },
  { "AMBULANCE", "PERCEPTION__CAR_TYPE__AMBULANCE", 1 },
  { "DANGERCAR", "PERCEPTION__CAR_TYPE__DANGERCAR", 2 },
  { "FIREENGINE", "PERCEPTION__CAR_TYPE__FIREENGINE", 3 },
  { "POLICECAR", "PERCEPTION__CAR_TYPE__POLICECAR", 4 },
};
static const ProtobufCIntRange perception__car_type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex perception__car_type__enum_values_by_name[5] =
{
  { "AMBULANCE", 1 },
  { "DANGERCAR", 2 },
  { "FIREENGINE", 3 },
  { "NORMAL", 0 },
  { "POLICECAR", 4 },
};
const ProtobufCEnumDescriptor perception__car_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "perception.CarType",
  "CarType",
  "Perception__CarType",
  "perception",
  5,
  perception__car_type__enum_values_by_number,
  5,
  perception__car_type__enum_values_by_name,
  1,
  perception__car_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue perception__car_status__enum_values_by_number[9] =
{
  { "STATUS_NORMAL", "PERCEPTION__CAR_STATUS__STATUS_NORMAL", 0 },
  { "RETROGRADE", "PERCEPTION__CAR_STATUS__RETROGRADE", 1 },
  { "OVER_SPEEDING", "PERCEPTION__CAR_STATUS__OVER_SPEEDING", 2 },
  { "LOW_SPEEDING", "PERCEPTION__CAR_STATUS__LOW_SPEEDING", 3 },
  { "ILLEGAL_PARKING", "PERCEPTION__CAR_STATUS__ILLEGAL_PARKING", 4 },
  { "LANE_PARKING", "PERCEPTION__CAR_STATUS__LANE_PARKING", 5 },
  { "AREA_PARKING", "PERCEPTION__CAR_STATUS__AREA_PARKING", 6 },
  { "CONTINUOUS_DIVERSION", "PERCEPTION__CAR_STATUS__CONTINUOUS_DIVERSION", 7 },
  { "LINE_PRESSING", "PERCEPTION__CAR_STATUS__LINE_PRESSING", 8 },
};
static const ProtobufCIntRange perception__car_status__value_ranges[] = {
{0, 0},{0, 9}
};
static const ProtobufCEnumValueIndex perception__car_status__enum_values_by_name[9] =
{
  { "AREA_PARKING", 6 },
  { "CONTINUOUS_DIVERSION", 7 },
  { "ILLEGAL_PARKING", 4 },
  { "LANE_PARKING", 5 },
  { "LINE_PRESSING", 8 },
  { "LOW_SPEEDING", 3 },
  { "OVER_SPEEDING", 2 },
  { "RETROGRADE", 1 },
  { "STATUS_NORMAL", 0 },
};
const ProtobufCEnumDescriptor perception__car_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "perception.CarStatus",
  "CarStatus",
  "Perception__CarStatus",
  "perception",
  9,
  perception__car_status__enum_values_by_number,
  9,
  perception__car_status__enum_values_by_name,
  1,
  perception__car_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue perception__ware_type__enum_values_by_number[4] =
{
  { "WARE_NONE", "PERCEPTION__WARE_TYPE__WARE_NONE", 0 },
  { "FULLLINE", "PERCEPTION__WARE_TYPE__FULLLINE", 1 },
  { "DOTTEDLINE", "PERCEPTION__WARE_TYPE__DOTTEDLINE", 2 },
  { "DOUBLEYELLOWLINE", "PERCEPTION__WARE_TYPE__DOUBLEYELLOWLINE", 3 },
};
static const ProtobufCIntRange perception__ware_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex perception__ware_type__enum_values_by_name[4] =
{
  { "DOTTEDLINE", 2 },
  { "DOUBLEYELLOWLINE", 3 },
  { "FULLLINE", 1 },
  { "WARE_NONE", 0 },
};
const ProtobufCEnumDescriptor perception__ware_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "perception.WareType",
  "WareType",
  "Perception__WareType",
  "perception",
  4,
  perception__ware_type__enum_values_by_number,
  4,
  perception__ware_type__enum_values_by_name,
  1,
  perception__ware_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
