/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: laser.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "laser.pb-c.h"
void   laser__timestamp__init
                     (Laser__Timestamp         *message)
{
  static const Laser__Timestamp init_value = LASER__TIMESTAMP__INIT;
  *message = init_value;
}
size_t laser__timestamp__get_packed_size
                     (const Laser__Timestamp *message)
{
  assert(message->base.descriptor == &laser__timestamp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t laser__timestamp__pack
                     (const Laser__Timestamp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &laser__timestamp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t laser__timestamp__pack_to_buffer
                     (const Laser__Timestamp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &laser__timestamp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Laser__Timestamp *
       laser__timestamp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Laser__Timestamp *)
     protobuf_c_message_unpack (&laser__timestamp__descriptor,
                                allocator, len, data);
}
void   laser__timestamp__free_unpacked
                     (Laser__Timestamp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &laser__timestamp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   laser__laser_obj__init
                     (Laser__LaserObj         *message)
{
  static const Laser__LaserObj init_value = LASER__LASER_OBJ__INIT;
  *message = init_value;
}
size_t laser__laser_obj__get_packed_size
                     (const Laser__LaserObj *message)
{
  assert(message->base.descriptor == &laser__laser_obj__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t laser__laser_obj__pack
                     (const Laser__LaserObj *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &laser__laser_obj__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t laser__laser_obj__pack_to_buffer
                     (const Laser__LaserObj *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &laser__laser_obj__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Laser__LaserObj *
       laser__laser_obj__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Laser__LaserObj *)
     protobuf_c_message_unpack (&laser__laser_obj__descriptor,
                                allocator, len, data);
}
void   laser__laser_obj__free_unpacked
                     (Laser__LaserObj *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &laser__laser_obj__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   laser__laser_msg__init
                     (Laser__LaserMsg         *message)
{
  static const Laser__LaserMsg init_value = LASER__LASER_MSG__INIT;
  *message = init_value;
}
size_t laser__laser_msg__get_packed_size
                     (const Laser__LaserMsg *message)
{
  assert(message->base.descriptor == &laser__laser_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t laser__laser_msg__pack
                     (const Laser__LaserMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &laser__laser_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t laser__laser_msg__pack_to_buffer
                     (const Laser__LaserMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &laser__laser_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Laser__LaserMsg *
       laser__laser_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Laser__LaserMsg *)
     protobuf_c_message_unpack (&laser__laser_msg__descriptor,
                                allocator, len, data);
}
void   laser__laser_msg__free_unpacked
                     (Laser__LaserMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &laser__laser_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor laser__timestamp__field_descriptors[2] =
{
  {
    "sec",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Laser__Timestamp, sec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "usec",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Laser__Timestamp, usec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned laser__timestamp__field_indices_by_name[] = {
  0,   /* field[0] = sec */
  1,   /* field[1] = usec */
};
static const ProtobufCIntRange laser__timestamp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor laser__timestamp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "laser.Timestamp",
  "Timestamp",
  "Laser__Timestamp",
  "laser",
  sizeof(Laser__Timestamp),
  2,
  laser__timestamp__field_descriptors,
  laser__timestamp__field_indices_by_name,
  1,  laser__timestamp__number_ranges,
  (ProtobufCMessageInit) laser__timestamp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor laser__laser_obj__field_descriptors[5] =
{
  {
    "object_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Laser__LaserObj, object_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lng",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Laser__LaserObj, lng),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lat",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Laser__LaserObj, lat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speed",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Laser__LaserObj, has_speed),
    offsetof(Laser__LaserObj, speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "heading",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Laser__LaserObj, has_heading),
    offsetof(Laser__LaserObj, heading),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned laser__laser_obj__field_indices_by_name[] = {
  4,   /* field[4] = heading */
  2,   /* field[2] = lat */
  1,   /* field[1] = lng */
  0,   /* field[0] = object_id */
  3,   /* field[3] = speed */
};
static const ProtobufCIntRange laser__laser_obj__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor laser__laser_obj__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "laser.LaserObj",
  "LaserObj",
  "Laser__LaserObj",
  "laser",
  sizeof(Laser__LaserObj),
  5,
  laser__laser_obj__field_descriptors,
  laser__laser_obj__field_indices_by_name,
  1,  laser__laser_obj__number_ranges,
  (ProtobufCMessageInit) laser__laser_obj__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor laser__laser_msg__field_descriptors[2] =
{
  {
    "objs",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Laser__LaserMsg, n_objs),
    offsetof(Laser__LaserMsg, objs),
    &laser__laser_obj__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Laser__LaserMsg, time),
    &laser__timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned laser__laser_msg__field_indices_by_name[] = {
  0,   /* field[0] = objs */
  1,   /* field[1] = time */
};
static const ProtobufCIntRange laser__laser_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor laser__laser_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "laser.LaserMsg",
  "LaserMsg",
  "Laser__LaserMsg",
  "laser",
  sizeof(Laser__LaserMsg),
  2,
  laser__laser_msg__field_descriptors,
  laser__laser_msg__field_indices_by_name,
  1,  laser__laser_msg__number_ranges,
  (ProtobufCMessageInit) laser__laser_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
